// Captions & Status database organized by mood/category

export interface Caption {
    text: string;
    emoji: string;
}

export interface CaptionCategory {
    slug: string;
    name: string;
    emoji: string;
    description: string;
    captions: Caption[];
}

export const captionCategories: CaptionCategory[] = [
    {
        slug: 'attitude',
        name: 'Attitude',
        emoji: '😏',
        description: 'Boss-level attitude captions for Instagram & WhatsApp',
        captions: [
            { text: 'I\'m not arguing, I\'m just explaining why I\'m right.', emoji: '😏' },
            { text: 'My attitude is based on how you treat me.', emoji: '💯' },
            { text: 'I don\'t have an attitude problem. You have a perception problem.', emoji: '🤷' },
            { text: 'Silent people have the loudest minds.', emoji: '🧠' },
            { text: 'I\'m not anti-social, I\'m selectively social.', emoji: '👑' },
            { text: 'Born to express, not to impress.', emoji: '🔥' },
            { text: 'Be yourself; everyone else is already taken.', emoji: '✨' },
            { text: 'Too glam to give a damn.', emoji: '💅' },
            { text: 'I\'m a limited edition — there\'s only one me.', emoji: '🦋' },
            { text: 'They told me I couldn\'t. That\'s why I did.', emoji: '💪' },
            { text: 'My silence is not weakness. It\'s the beginning of my revenge.', emoji: '😈' },
            { text: 'I\'m not perfect but I\'m limited edition.', emoji: '🏆' },
            { text: 'Savage, not average.', emoji: '🐍' },
            { text: 'If you don\'t like me, remember it\'s mind over matter. I don\'t mind and you don\'t matter.', emoji: '😎' },
            { text: 'I\'m the king of my own kingdom.', emoji: '👑' },
            { text: 'Confidence level: Selfie with no filter.', emoji: '📸' },
            { text: 'Too busy being a boss to worry about haters.', emoji: '💼' },
            { text: 'Winners focus on winning. Losers focus on winners.', emoji: '🏆' },
            { text: 'My back is not a voicemail, say it to my face.', emoji: '🗣️' },
            { text: 'I don\'t look back unless there\'s a good view.', emoji: '👀' },
        ],
    },
    {
        slug: 'love',
        name: 'Love & Romance',
        emoji: '❤️',
        description: 'Romantic captions for couples and love posts',
        captions: [
            { text: 'You are my today and all of my tomorrows.', emoji: '💕' },
            { text: 'Every love story is beautiful, but ours is my favorite.', emoji: '📖' },
            { text: 'In a sea of people, my eyes will always search for you.', emoji: '🌊' },
            { text: 'You\'re the reason I believe in love.', emoji: '💖' },
            { text: 'I fell in love the way you fall asleep — slowly, then all at once.', emoji: '🌙' },
            { text: 'My heart is and always will be yours.', emoji: '❤️' },
            { text: 'Together is a wonderful place to be.', emoji: '🤝' },
            { text: 'You had me at hello.', emoji: '👋' },
            { text: 'I choose you. And I\'ll choose you over and over.', emoji: '💍' },
            { text: 'Love isn\'t something you find. Love is something that finds you.', emoji: '🔍' },
            { text: 'You make my heart smile.', emoji: '😊' },
            { text: 'I love you more than coffee, but not always before coffee.', emoji: '☕' },
            { text: 'You are my sun, my moon, and all my stars.', emoji: '🌟' },
            { text: 'Home is wherever I\'m with you.', emoji: '🏡' },
            { text: 'I want all of you, forever, you and me, every day.', emoji: '💞' },
            { text: 'You stole my heart, but I\'ll let you keep it.', emoji: '💘' },
            { text: 'I didn\'t choose you, my heart did.', emoji: '❣️' },
            { text: 'Life is better when I\'m with you.', emoji: '🌈' },
            { text: 'You\'re the missing piece I\'ve been looking for.', emoji: '🧩' },
            { text: 'Falling for you was the best mistake I ever made.', emoji: '🍂' },
        ],
    },
    {
        slug: 'sad',
        name: 'Sad & Emotional',
        emoji: '😢',
        description: 'Emotional captions for when words carry the weight',
        captions: [
            { text: 'The worst kind of pain is when you\'re smiling to stop the tears from falling.', emoji: '😢' },
            { text: 'Sometimes you have to accept that some people can only be in your heart, not in your life.', emoji: '💔' },
            { text: 'I\'m not okay, but I smile anyway.', emoji: '🥀' },
            { text: 'The saddest thing is when you\'re feeling lonely among people you know.', emoji: '🌧️' },
            { text: 'Missing someone is a part of loving them.', emoji: '💭' },
            { text: 'Every smile has a story of a struggle behind it.', emoji: '😔' },
            { text: 'Sometimes it\'s better to be alone. No one can hurt you.', emoji: '🖤' },
            { text: 'The hardest part of dreaming about someone you love is having to wake up.', emoji: '🌑' },
            { text: 'Tears are words the heart can\'t express.', emoji: '💧' },
            { text: 'I\'m fighting battles nobody knows about.', emoji: '⚔️' },
            { text: 'Don\'t cry because it\'s over, smile because it happened.', emoji: '🌸' },
            { text: 'I gave you my heart, I just didn\'t expect to get it back in pieces.', emoji: '💔' },
            { text: 'The pain you feel today is the strength you feel tomorrow.', emoji: '🌅' },
            { text: 'Not all wounds are visible.', emoji: '🩹' },
            { text: 'I\'m tired of trying, sick of crying, I know I\'ve been smiling but inside I\'m dying.', emoji: '😶' },
        ],
    },
    {
        slug: 'motivational',
        name: 'Motivational',
        emoji: '💪',
        description: 'Motivational captions to inspire and empower',
        captions: [
            { text: 'Dream it. Believe it. Build it.', emoji: '🏗️' },
            { text: 'Stay hungry, stay foolish.', emoji: '🔥' },
            { text: 'The only way to do great work is to love what you do.', emoji: '❤️' },
            { text: 'Don\'t stop when you\'re tired. Stop when you\'re done.', emoji: '💪' },
            { text: 'Success is not final, failure is not fatal.', emoji: '🏆' },
            { text: 'Work hard in silence, let success make the noise.', emoji: '🤫' },
            { text: 'Hustle until your haters ask if you\'re hiring.', emoji: '💼' },
            { text: 'Your only limit is your mind.', emoji: '🧠' },
            { text: 'Great things never come from comfort zones.', emoji: '🚀' },
            { text: 'Be so good they can\'t ignore you.', emoji: '⭐' },
            { text: 'The comeback is always stronger than the setback.', emoji: '💥' },
            { text: 'Fall seven times, stand up eight.', emoji: '🥊' },
            { text: 'Turn your wounds into wisdom.', emoji: '📚' },
            { text: 'Make today so awesome that yesterday gets jealous.', emoji: '🌟' },
            { text: 'Believe you can and you\'re halfway there.', emoji: '🎯' },
            { text: 'Small progress is still progress.', emoji: '📈' },
            { text: 'Difficult roads often lead to beautiful destinations.', emoji: '🛤️' },
            { text: 'Stars can\'t shine without darkness.', emoji: '✨' },
            { text: 'Wake up with determination, go to bed with satisfaction.', emoji: '🌅' },
            { text: 'Champions keep playing until they get it right.', emoji: '🏅' },
        ],
    },
    {
        slug: 'funny',
        name: 'Funny',
        emoji: '😂',
        description: 'Hilarious captions that make everyone laugh',
        captions: [
            { text: 'I\'m not lazy, I\'m on energy saving mode.', emoji: '🔋' },
            { text: 'My bed is a magical place where I suddenly remember everything I forgot to do.', emoji: '🛏️' },
            { text: 'I need a six-month holiday, twice a year.', emoji: '🏝️' },
            { text: 'I\'m not short, I\'m concentrated awesome.', emoji: '🧪' },
            { text: 'Life is short. Smile while you still have teeth.', emoji: '😁' },
            { text: 'I put the "Pro" in procrastinate.', emoji: '🏆' },
            { text: 'Friday is my second favorite F-word. Food is my first.', emoji: '🍕' },
            { text: 'I followed my heart, and it led me to the fridge.', emoji: '❤️' },
            { text: 'Running late is my cardio.', emoji: '🏃' },
            { text: 'I\'m on a seafood diet. I see food, I eat it.', emoji: '🦞' },
            { text: 'Common sense is like deodorant. People who need it most never use it.', emoji: '🧴' },
            { text: 'My wallet is like an onion. Opening it makes me cry.', emoji: '🧅' },
            { text: 'I\'m not weird, I\'m a limited edition.', emoji: '🎭' },
            { text: 'Sarcasm: because beating people up is illegal.', emoji: '⚖️' },
            { text: 'I came. I saw. I made it awkward.', emoji: '🤝' },
        ],
    },
    {
        slug: 'gaming',
        name: 'Gaming',
        emoji: '🎮',
        description: 'Epic gaming captions for profiles and streams',
        captions: [
            { text: 'Eat. Sleep. Game. Repeat.', emoji: '🎮' },
            { text: 'Respawn and try again.', emoji: '🔄' },
            { text: 'I don\'t need therapy, I just need to play.', emoji: '🕹️' },
            { text: 'GG EZ', emoji: '🏆' },
            { text: 'Born to game, forced to work.', emoji: '💼' },
            { text: 'One more game... said every gamer ever.', emoji: '😅' },
            { text: 'In my defense, I was left unsupervised near a controller.', emoji: '🎮' },
            { text: 'My kill count speaks louder than words.', emoji: '💀' },
            { text: 'Reality is just a crappy game with amazing graphics.', emoji: '🌍' },
            { text: 'I paused my game to be here.', emoji: '⏸️' },
            { text: 'Lag is the only enemy I can\'t defeat.', emoji: '📶' },
            { text: 'Winners train, losers complain.', emoji: '🏅' },
            { text: 'Don\'t follow me, you won\'t make it.', emoji: '🐾' },
            { text: 'My controller is an extension of my soul.', emoji: '🎮' },
            { text: 'Pro player loading... please wait.', emoji: '⏳' },
        ],
    },
    {
        slug: 'selfie',
        name: 'Selfie',
        emoji: '🤳',
        description: 'Perfect captions for your selfie posts',
        captions: [
            { text: 'But first, let me take a selfie.', emoji: '🤳' },
            { text: 'I woke up like this. Flawless.', emoji: '💅' },
            { text: 'Be your own kind of beautiful.', emoji: '🌸' },
            { text: 'Life isn\'t perfect but your selfie can be.', emoji: '📸' },
            { text: 'Felt cute, might delete later.', emoji: '😊' },
            { text: 'No filter needed.', emoji: '✨' },
            { text: 'Smile big, laugh often, never take this life for granted.', emoji: '😁' },
            { text: 'Confidence looks good on me.', emoji: '💪' },
            { text: 'I\'m not taking selfies, I\'m doing a photo study of myself.', emoji: '🔬' },
            { text: 'Life is too short for boring hair and bad selfies.', emoji: '💇' },
            { text: 'Warning: My selfie game is strong.', emoji: '⚠️' },
            { text: 'Me, myself, and I.', emoji: '👋' },
            { text: 'In a world full of trends, I want to remain a classic.', emoji: '🎩' },
            { text: 'They say don\'t try too hard. I say try my selfie.', emoji: '📱' },
            { text: 'Sun-kissed and selfie-obsessed.', emoji: '☀️' },
        ],
    },
    {
        slug: 'birthday',
        name: 'Birthday',
        emoji: '🎂',
        description: 'Birthday captions and wishes for the special day',
        captions: [
            { text: 'Another year older but definitely not wiser.', emoji: '🎂' },
            { text: 'It\'s my birthday! Time to eat cake and celebrate me.', emoji: '🎉' },
            { text: 'Cheers to another trip around the sun.', emoji: '☀️' },
            { text: 'On this day, a queen/king was born.', emoji: '👑' },
            { text: 'Making my years count, not counting my years.', emoji: '🥂' },
            { text: 'Birthday calories don\'t count.', emoji: '🍰' },
            { text: 'Sassy since birth.', emoji: '💃' },
            { text: 'Keep calm and celebrate my birthday.', emoji: '🎈' },
            { text: 'Aged to perfection.', emoji: '🍷' },
            { text: 'It took me [age] years to look this good.', emoji: '😎' },
            { text: 'Birthday vibes only.', emoji: '✨' },
            { text: 'New age, same amazing me.', emoji: '🌟' },
            { text: 'Thanks for making my birthday special, from the bottom of my cake.', emoji: '🎂' },
            { text: 'Living my best life, one birthday at a time.', emoji: '🎊' },
            { text: 'Born to stand out.', emoji: '⭐' },
        ],
    },
    {
        slug: 'friendship',
        name: 'Friendship',
        emoji: '👯',
        description: 'Captions for your best friend posts and squad pics',
        captions: [
            { text: 'Good friends are like stars. You don\'t always see them, but you know they\'re always there.', emoji: '⭐' },
            { text: 'Friends who slay together, stay together.', emoji: '💅' },
            { text: 'Life was meant for best friends and good adventures.', emoji: '🗺️' },
            { text: 'A true friend is one soul in two bodies.', emoji: '👯' },
            { text: 'Friends buy you food. Best friends eat your food.', emoji: '🍟' },
            { text: 'We go together like coffee and donuts.', emoji: '☕' },
            { text: 'Real queens fix each other\'s crowns.', emoji: '👑' },
            { text: 'Side by side or miles apart, friends are always close to the heart.', emoji: '❤️' },
            { text: 'I\'d rather walk with a friend in the dark than alone in the light.', emoji: '🌙' },
            { text: 'My best friend is the one who brings out the best in me.', emoji: '✨' },
            { text: 'Friends don\'t let friends do stupid things... alone.', emoji: '😂' },
            { text: 'No friendship is an accident.', emoji: '🎯' },
            { text: 'Life is better with true friends.', emoji: '🌈' },
            { text: 'Finding friends with the same mental disorder: priceless.', emoji: '🤪' },
            { text: 'We\'ll be the old ladies causing trouble in the nursing home.', emoji: '👵' },
        ],
    },
    {
        slug: 'travel',
        name: 'Travel',
        emoji: '✈️',
        description: 'Adventure captions for wanderlust souls',
        captions: [
            { text: 'Adventure awaits.', emoji: '🗺️' },
            { text: 'Not all who wander are lost.', emoji: '🧭' },
            { text: 'Travel far enough to meet yourself.', emoji: '✈️' },
            { text: 'Collect moments, not things.', emoji: '📸' },
            { text: 'The world is a book, and those who do not travel read only one page.', emoji: '📖' },
            { text: 'Wanderlust: a strong desire to travel.', emoji: '🌍' },
            { text: 'Take only memories, leave only footprints.', emoji: '👣' },
            { text: 'Life is short and the world is wide.', emoji: '🌎' },
            { text: 'Let\'s find some beautiful place to get lost.', emoji: '🏔️' },
            { text: 'Catch flights, not feelings.', emoji: '✈️' },
            { text: 'Born to explore.', emoji: '🧗' },
            { text: 'Sandy toes and sunkissed nose.', emoji: '🏖️' },
            { text: 'Travel is the only thing you buy that makes you richer.', emoji: '💰' },
            { text: 'I\'ve got a bad case of wanderlust.', emoji: '🌴' },
            { text: 'Jobs fill your pocket, adventures fill your soul.', emoji: '🎒' },
        ],
    },
];
