// Translated homepage SEO content by locale
// Returns localized HTML content + FAQ items for the homepage bottom section

import { Locale } from './i18n';

interface HomepageSEO {
    content: string;
    faqItems: { question: string; answer: string }[];
}

const homepageSEOContent: Record<Locale, HomepageSEO> = {
    en: {
        content: `<p>Looking for a <strong>stylish name generator</strong> or <strong>stylish name maker</strong>? You're in the right place! Our free tool lets you create <strong>stylish name designs</strong> with cool fonts, fancy symbols, and unique decorations. Just type your name, pick a style, and copy it — that's it. Works on <strong>Instagram, PUBG, Free Fire, TikTok, WhatsApp, Facebook</strong>, and every other app.</p>
<p>You'll see this tool called many things around the web — <strong>stylish name maker</strong>, <strong>name style font</strong> generator, <strong>stylish naam</strong> maker (in South Asia), <strong>nama style</strong> editor (in Indonesia), or just plain <strong>name style</strong> generator. They're all the same idea: take your regular name, dress it up with Unicode fonts and symbols, and paste it anywhere.</p>
<figure style="text-align:center;margin:1.5rem 0"><img src="/images/stylish-names-sample.webp" alt="Stylish name examples with cool fonts and decorations - Estelle, Murad, Tauseef, Kumar" width="724" height="1024" loading="lazy" style="max-width:100%;height:auto;border-radius:12px" /><figcaption style="font-size:0.85rem;color:#888;margin-top:0.5rem">Examples of stylish names generated by our tool</figcaption></figure>
<h3>🎮 Stylish Names for Gaming</h3>
<p>Our <strong>gaming name generator</strong> is built for players. Create a <strong>PUBG stylish name</strong> with cool symbols, or generate a <strong>Free Fire stylish name</strong> that fits the 12-character limit. We also support <strong>BGMI stylish names</strong>, Fortnite, COD Mobile, and Roblox. Every style is tested to work in-game — no broken characters.</p>
<figure style="text-align:center;margin:1.5rem 0"><img src="/images/cool-symbols.webp" alt="Cool symbols and fancy text names with decorative borders for gaming and social media profiles" width="724" height="1024" loading="lazy" style="max-width:100%;height:auto;border-radius:12px" /><figcaption style="font-size:0.85rem;color:#888;margin-top:0.5rem">Cool symbols and fancy text for gaming names</figcaption></figure>
<h3>📱 Stylish Names for Social Media</h3>
<p>Make your profile pop with a unique <strong>Instagram stylish name</strong> for your bio. Our <strong>TikTok stylish name</strong> generator creates fonts that look amazing on your profile. Use our <strong>FB stylish name maker</strong> for a cool Facebook display name. And for messaging, our <strong>WhatsApp stylish name</strong> styles are perfect for status and profile.</p>
<figure style="text-align:center;margin:1.5rem 0"><img src="/images/facebook-stylish-name.webp" alt="Facebook stylish name generator showing stunning decorated names for FB profile" width="768" height="432" loading="lazy" style="max-width:100%;height:auto;border-radius:12px" /><figcaption style="font-size:0.85rem;color:#888;margin-top:0.5rem">Stylish names for Facebook profiles</figcaption></figure>
<h3>👦👧 Stylish Names for Boys & Girls</h3>
<p>Looking for a <strong>stylish name for boy</strong>? Try our cool, dashing, and attitude-filled designs. Or find a <strong>stylish name for girl</strong> with hearts, flowers, and cute symbols. We also have <strong>beautiful stylish names</strong> for anyone who wants something elegant and eye-catching.</p>
<figure style="text-align:center;margin:1.5rem 0"><img src="/images/aesthetic-fonts.webp" alt="Aesthetic font styles showing beautiful decorated name designs with hearts and flowers" width="724" height="1024" loading="lazy" style="max-width:100%;height:auto;border-radius:12px" /><figcaption style="font-size:0.85rem;color:#888;margin-top:0.5rem">Aesthetic font designs for girls and boys</figcaption></figure>
<h3>💑 Couple & Group Names</h3>
<p>Create matching <strong>stylish couple names</strong> with romantic fonts and love symbols. Or use our <strong>stylish friends group name</strong> generator for your WhatsApp group, gaming squad, or Discord server. We even have <strong>mafia stylish names</strong> if you want something bold and powerful.</p>
<h3>🛠️ How Our Stylish Text Generator Works</h3>
<p>Our <strong>stylish text generator</strong> uses Unicode characters — these are real text characters, not images. That means they work everywhere: any phone, any browser, any app. No downloads, no sign-ups. Just type your <strong>name style</strong> and copy. We have over 1000 <strong>stylish text name</strong> designs including cursive, bold, gothic, bubble, italic, and decorated fonts.</p>
<figure style="text-align:center;margin:1.5rem 0"><img src="/images/cool-fonts.webp" alt="Cool fonts showcase with multiple Unicode text styles - cursive, bold, gothic, bubble, and decorated fonts" width="768" height="768" loading="lazy" style="max-width:100%;height:auto;border-radius:12px" /><figcaption style="font-size:0.85rem;color:#888;margin-top:0.5rem">Cool font styles available in our generator</figcaption></figure>
<h3>🔤 Fancy Text Generator & Cool Fonts</h3>
<p>Many people call this a <strong>fancy text generator</strong>, <strong>cool font generator</strong>, or <strong>Instagram font generator</strong> — and that's exactly what it is. We turn your regular keyboard letters into beautiful Unicode font styles: <strong>cursive text</strong>, <strong>bold italic</strong>, <strong>aesthetic fonts</strong>, gothic, bubble letters, small caps, upside-down text, and many more. Whether you call them <em>fancy fonts</em>, <em>cool fonts</em>, <em>stylish fonts</em>, or <em>aesthetic fonts</em>, they all work on Instagram bio, Twitter, TikTok username, Discord nickname, and any text field that accepts Unicode.</p>
<h3>📶 More Cool Tools</h3>
<p>Besides the <strong>stylish name design</strong> generator, we also have an <strong>invisible text generator</strong> for blank names, a <strong>text repeater</strong>, a <strong>zalgo text generator</strong> for creepy effects, a <strong>strikethrough text</strong> tool, <strong>mirror text</strong> and <strong>upside down text</strong> generators, and 400+ special symbols you can copy. All free, all instant.</p>
<h3>💡 Quick Tips</h3>
<ul><li>Keep names short (3–15 characters) for the best look</li><li>Try different categories — gaming, cute, cool, fancy, love</li><li>Mix styles with decorators for something totally unique</li><li>Test your name in the app before finalizing — some platforms have limits</li><li>Use our compatibility checker to see which platforms support your name</li></ul>`,
        faqItems: [
            { question: 'What is a stylish name generator?', answer: 'A stylish name generator (also called a stylish name maker, name style font tool, or stylish naam maker) is a free tool that turns your plain text into cool, fancy-looking names using special Unicode fonts and symbols. You just type your name, pick a style you like, and copy it. It works on Instagram, PUBG, Free Fire, TikTok, WhatsApp, and pretty much anywhere.' },
            { question: 'What does "naam style" or "stylish naam" mean?', answer: '"Naam" means "name" in Hindi, Urdu, and Bengali — so "naam style" and "stylish naam" are just ways of saying "stylish name" used by users in South Asia. Whichever way you spell it (stylish name, stylish naam, stalish name, nama style), the tool works exactly the same — type your name above and pick a style.' },
            { question: 'Is this also a fancy text or Instagram font generator?', answer: 'Yes — same tool, different names. A "fancy text generator", "cool font generator", "Instagram font generator", and "aesthetic font" maker all do the same thing: convert your regular text into Unicode font styles you can copy and paste anywhere. Use it for your Instagram bio, Twitter, TikTok username, Discord nickname, or any social profile.' },
            { question: 'Will the fonts work on Instagram, Twitter, and Discord?', answer: 'Yes. We use Unicode characters, which are the same standard those apps use to display text. So whatever font style you copy from here will appear identically on Instagram bio, Twitter, TikTok, Discord, Snapchat, Facebook, WhatsApp — basically every modern app and browser.' },
            { question: 'How to make a stylish name for PUBG and Free Fire?', answer: 'Just type your name in the box above, scroll through the styles, and tap on one you like — it copies instantly. Then paste it as your in-game username. Our generator has 1000+ fonts that work on PUBG Mobile, Free Fire, BGMI, and other games.' },
            { question: 'Can I make stylish names for boys and girls?', answer: 'Yes! We have separate categories for boys (cool, dashing, attitude styles) and girls (cute, beautiful, lovely styles). Visit our Boy Names or Girl Names page for styles made just for you.' },
            { question: 'Do stylish names work on Instagram and TikTok?', answer: 'Yes, 100%. Our names use Unicode characters that work on Instagram bio, TikTok username, WhatsApp status, Facebook profile, and all social media apps. No special app needed — just copy and paste.' },
            { question: 'Is this stylish name generator free?', answer: 'Totally free! No sign-up, no downloads, no limits. Generate as many stylish names as you want. We also have free tools like invisible text, text repeater, zalgo text, and 400+ symbols to copy.' },
            { question: 'What other tools do you have?', answer: 'Besides the stylish name generator, we have an invisible text generator (for blank names in games), text repeater, zalgo/glitch text maker, strikethrough and text effects, upside down and mirror text, 400+ symbols keyboard, Instagram captions, and a character counter for checking platform limits.' },
        ],
    },

    de: {
        content: `<p>Suchen Sie einen <strong>stylischen Namensgenerator</strong>? Hier sind Sie richtig! Unser kostenloses Tool erstellt <strong>stylische Namensdesigns</strong> mit coolen Schriftarten, ausgefallenen Symbolen und einzigartigen Dekorationen. Einfach Namen eingeben, Stil wählen und kopieren. Funktioniert auf <strong>Instagram, PUBG, Free Fire, TikTok, WhatsApp, Facebook</strong> und jeder anderen App.</p>
<h3>🎮 Stylische Gaming-Namen</h3>
<p>Unser <strong>Gaming-Namensgenerator</strong> ist für Spieler gemacht. Erstellen Sie einen <strong>PUBG stylischen Namen</strong> mit coolen Symbolen oder einen <strong>Free Fire stylischen Namen</strong> innerhalb des 12-Zeichen-Limits. Auch <strong>BGMI</strong>, Fortnite, COD Mobile und Roblox werden unterstützt.</p>
<h3>📱 Stylische Namen für Social Media</h3>
<p>Machen Sie Ihr Profil einzigartig mit einem <strong>Instagram stylischen Namen</strong>. Unser <strong>TikTok stylischer Name</strong> Generator erstellt Schriften, die auf Ihrem Profil großartig aussehen. Auch <strong>WhatsApp</strong>, <strong>Facebook</strong> und <strong>Discord</strong> werden unterstützt.</p>
<h3>👦👧 Stylische Namen für Jungs & Mädchen</h3>
<p>Suchen Sie einen <strong>stylischen Namen für Jungs</strong>? Probieren Sie unsere coolen Attitude-Designs. Oder finden Sie einen <strong>stylischen Namen für Mädchen</strong> mit Herzen, Blumen und süßen Symbolen.</p>
<h3>🛠️ Wie unser Generator funktioniert</h3>
<p>Unser <strong>stylischer Textgenerator</strong> verwendet Unicode-Zeichen — echte Textzeichen, keine Bilder. Das heißt, sie funktionieren überall: jedes Handy, jeder Browser, jede App. Kein Download, keine Anmeldung. Über 1000 Designs.</p>
<h3>💡 Schnelle Tipps</h3>
<ul><li>Halten Sie Namen kurz (3–15 Zeichen)</li><li>Probieren Sie verschiedene Kategorien — Gaming, Cute, Cool, Fancy, Love</li><li>Mischen Sie Stile mit Dekorationen für etwas Einzigartiges</li><li>Testen Sie Ihren Namen in der App — einige Plattformen haben Limits</li></ul>`,
        faqItems: [
            { question: 'Was ist ein stylischer Namensgenerator?', answer: 'Ein stylischer Namensgenerator verwandelt Ihren normalen Text in coole, ausgefallene Namen mit speziellen Unicode-Schriftarten und Symbolen. Namen eingeben, Stil wählen, kopieren. Funktioniert auf Instagram, PUBG, Free Fire, TikTok, WhatsApp und überall.' },
            { question: 'Wie erstelle ich einen stylischen PUBG- oder Free Fire-Namen?', answer: 'Geben Sie Ihren Namen oben ein, scrollen Sie durch die Stile und tippen Sie auf einen — er wird sofort kopiert. Dann einfügen als In-Game-Name. Über 1000 Schriften für PUBG Mobile, Free Fire und BGMI.' },
            { question: 'Funktionieren stylische Namen auf Instagram und TikTok?', answer: 'Ja, 100%. Unsere Namen verwenden Unicode-Zeichen, die auf Instagram Bio, TikTok Benutzername, WhatsApp Status und allen Social-Media-Apps funktionieren.' },
            { question: 'Ist dieser stylische Namensgenerator kostenlos?', answer: 'Völlig kostenlos! Keine Anmeldung, keine Downloads, keine Limits. Erstellen Sie so viele stylische Namen wie Sie möchten.' },
        ],
    },

    fr: {
        content: `<p>Vous cherchez un <strong>générateur de noms stylés</strong> ? Vous êtes au bon endroit ! Notre outil gratuit crée des <strong>designs de noms stylés</strong> avec des polices cool, des symboles et des décorations uniques. Tapez votre nom, choisissez un style et copiez — c'est tout ! Fonctionne sur <strong>Instagram, PUBG, Free Fire, TikTok, WhatsApp, Facebook</strong> et toutes les autres apps.</p>
<h3>🎮 Noms Stylés pour le Gaming</h3>
<p>Notre <strong>générateur de noms gaming</strong> est fait pour les joueurs. Créez un <strong>nom PUBG stylé</strong> avec des symboles cool ou un <strong>nom Free Fire stylé</strong> dans la limite de 12 caractères. Aussi <strong>BGMI</strong>, Fortnite, COD Mobile et Roblox.</p>
<h3>📱 Noms Stylés pour les Réseaux Sociaux</h3>
<p>Faites ressortir votre profil avec un <strong>nom Instagram stylé</strong> unique. Notre générateur <strong>TikTok</strong> crée des polices magnifiques. Aussi pour <strong>WhatsApp</strong>, <strong>Facebook</strong> et <strong>Discord</strong>.</p>
<h3>👦👧 Noms Stylés pour Garçons & Filles</h3>
<p>Cherchez un <strong>nom stylé pour garçon</strong> avec des designs cool et audacieux. Ou un <strong>nom stylé pour fille</strong> avec des cœurs, fleurs et symboles mignons.</p>
<h3>🛠️ Comment ça Marche</h3>
<p>Notre <strong>générateur de texte stylé</strong> utilise des caractères Unicode — de vrais caractères, pas des images. Ils fonctionnent partout. Plus de 1000 designs incluant cursif, gras, gothique et bulle.</p>
<h3>💡 Astuces Rapides</h3>
<ul><li>Gardez les noms courts (3–15 caractères)</li><li>Essayez différentes catégories — gaming, cute, cool, fancy, love</li><li>Mélangez les styles avec des décorations pour quelque chose d'unique</li><li>Testez votre nom dans l'app — certaines plateformes ont des limites</li></ul>`,
        faqItems: [
            { question: 'Qu\'est-ce qu\'un générateur de noms stylés ?', answer: 'Un générateur de noms stylés transforme votre texte en noms cool avec des polices Unicode spéciales. Tapez, choisissez, copiez. Fonctionne sur Instagram, PUBG, Free Fire, TikTok, WhatsApp et partout.' },
            { question: 'Comment faire un nom stylé pour PUBG et Free Fire ?', answer: 'Tapez votre nom ci-dessus, faites défiler les styles et tapez sur celui que vous aimez — il est copié instantanément. Collez-le comme nom in-game.' },
            { question: 'Les noms stylés fonctionnent-ils sur Instagram et TikTok ?', answer: 'Oui, 100%. Nos noms utilisent des caractères Unicode qui fonctionnent sur Instagram bio, TikTok, WhatsApp et toutes les apps.' },
            { question: 'Ce générateur est-il gratuit ?', answer: 'Totalement gratuit ! Pas d\'inscription, pas de téléchargement, pas de limites.' },
        ],
    },

    es: {
        content: `<p>¿Buscas un <strong>generador de nombres con estilo</strong>? ¡Estás en el lugar correcto! Nuestra herramienta gratuita crea <strong>diseños de nombres con estilo</strong> con fuentes cool, símbolos y decoraciones únicas. Escribe tu nombre, elige un estilo y copia — ¡así de fácil! Funciona en <strong>Instagram, PUBG, Free Fire, TikTok, WhatsApp, Facebook</strong> y todas las apps.</p>
<h3>🎮 Nombres con Estilo para Gaming</h3>
<p>Nuestro <strong>generador de nombres gaming</strong> está hecho para jugadores. Crea un <strong>nombre PUBG con estilo</strong> o un <strong>nombre Free Fire con estilo</strong> dentro del límite de 12 caracteres. También <strong>BGMI</strong>, Fortnite, COD Mobile y Roblox.</p>
<h3>📱 Nombres con Estilo para Redes Sociales</h3>
<p>Haz que tu perfil destaque con un <strong>nombre Instagram con estilo</strong> único. También para <strong>TikTok</strong>, <strong>WhatsApp</strong>, <strong>Facebook</strong> y <strong>Discord</strong>.</p>
<h3>👦👧 Nombres para Chicos y Chicas</h3>
<p>¿Buscas un <strong>nombre con estilo para chico</strong>? Prueba nuestros diseños cool y con actitud. O un <strong>nombre para chica</strong> con corazones, flores y símbolos lindos.</p>
<h3>🛠️ Cómo Funciona</h3>
<p>Nuestro <strong>generador de texto con estilo</strong> usa caracteres Unicode — caracteres reales, no imágenes. Funcionan en todos lados. Más de 1000 diseños incluyendo cursiva, negrita, gótico y burbuja.</p>
<h3>💡 Consejos Rápidos</h3>
<ul><li>Mantén los nombres cortos (3–15 caracteres)</li><li>Prueba diferentes categorías — gaming, cute, cool, fancy, love</li><li>Mezcla estilos con decoraciones para algo único</li></ul>`,
        faqItems: [
            { question: '¿Qué es un generador de nombres con estilo?', answer: 'Un generador que transforma tu texto en nombres cool con fuentes Unicode especiales. Escribe, elige, copia. Funciona en Instagram, PUBG, Free Fire, TikTok, WhatsApp y en todas partes.' },
            { question: '¿Cómo hacer un nombre con estilo para PUBG y Free Fire?', answer: 'Escribe tu nombre arriba, desplázate por los estilos y toca el que te guste — se copia al instante. Pégalo como tu nombre en el juego.' },
            { question: '¿Los nombres con estilo funcionan en Instagram y TikTok?', answer: 'Sí, 100%. Nuestros nombres usan caracteres Unicode que funcionan en Instagram bio, TikTok, WhatsApp y todas las apps.' },
            { question: '¿Es gratis este generador?', answer: '¡Totalmente gratis! Sin registro, sin descargas, sin límites.' },
        ],
    },

    pt: {
        content: `<p>Procurando um <strong>gerador de nomes estilosos</strong>? Você está no lugar certo! Nossa ferramenta gratuita cria <strong>designs de nomes estilosos</strong> com fontes legais, símbolos e decorações únicas. Digite seu nome, escolha um estilo e copie — simples assim! Funciona no <strong>Instagram, PUBG, Free Fire, TikTok, WhatsApp, Facebook</strong> e todos os outros apps.</p>
<h3>🎮 Nomes Estilosos para Gaming</h3>
<p>Nosso <strong>gerador de nomes gaming</strong> é feito para jogadores. Crie um <strong>nome PUBG estiloso</strong> ou um <strong>nome Free Fire estiloso</strong> dentro do limite de 12 caracteres. Também <strong>BGMI</strong>, Fortnite, COD Mobile e Roblox.</p>
<h3>📱 Nomes Estilosos para Redes Sociais</h3>
<p>Destaque seu perfil com um <strong>nome Instagram estiloso</strong> único. Também para <strong>TikTok</strong>, <strong>WhatsApp</strong>, <strong>Facebook</strong> e <strong>Discord</strong>.</p>
<h3>👦👧 Nomes para Meninos e Meninas</h3>
<p>Procurando um <strong>nome estiloso para menino</strong>? Experimente nossos designs legais com atitude. Ou um <strong>nome para menina</strong> com corações, flores e símbolos fofos.</p>
<h3>🛠️ Como Funciona</h3>
<p>Nosso <strong>gerador de texto estiloso</strong> usa caracteres Unicode — caracteres reais, não imagens. Funcionam em todo lugar. Mais de 1000 designs incluindo cursivo, negrito, gótico e bolha.</p>`,
        faqItems: [
            { question: 'O que é um gerador de nomes estilosos?', answer: 'Um gerador que transforma seu texto em nomes legais com fontes Unicode especiais. Digite, escolha, copie. Funciona no Instagram, PUBG, Free Fire, TikTok, WhatsApp e em todos os lugares.' },
            { question: 'Como fazer um nome estiloso para PUBG e Free Fire?', answer: 'Digite seu nome acima, role pelos estilos e toque no que gostar — copia na hora. Cole como nome no jogo.' },
            { question: 'Nomes estilosos funcionam no Instagram e TikTok?', answer: 'Sim, 100%. Nossos nomes usam caracteres Unicode que funcionam no Instagram bio, TikTok, WhatsApp e todos os apps.' },
            { question: 'Este gerador é gratuito?', answer: 'Totalmente grátis! Sem cadastro, sem downloads, sem limites.' },
        ],
    },

    it: {
        content: `<p>Cerchi un <strong>generatore di nomi stilosi</strong>? Sei nel posto giusto! Il nostro strumento gratuito crea <strong>nomi stilosi</strong> con font fantastici, simboli e decorazioni uniche. Scrivi il tuo nome, scegli uno stile e copia — tutto qui! Funziona su <strong>Instagram, PUBG, Free Fire, TikTok, WhatsApp, Facebook</strong> e tutte le altre app.</p>
<h3>🎮 Nomi Stilosi per il Gaming</h3>
<p>Il nostro <strong>generatore di nomi gaming</strong> è fatto per i giocatori. Crea un <strong>nome PUBG stiloso</strong> o un <strong>nome Free Fire stiloso</strong>. Anche <strong>BGMI</strong>, Fortnite, COD Mobile e Roblox.</p>
<h3>📱 Nomi Stilosi per i Social Media</h3>
<p>Fai risaltare il tuo profilo con un <strong>nome Instagram stiloso</strong> unico. Anche per <strong>TikTok</strong>, <strong>WhatsApp</strong>, <strong>Facebook</strong> e <strong>Discord</strong>.</p>
<h3>🛠️ Come Funziona</h3>
<p>Il nostro <strong>generatore di testo stiloso</strong> usa caratteri Unicode — caratteri reali, non immagini. Funzionano ovunque. Oltre 1000 design.</p>`,
        faqItems: [
            { question: 'Cos\'è un generatore di nomi stilosi?', answer: 'Uno strumento che trasforma il tuo testo in nomi fantastici con font Unicode speciali. Scrivi, scegli, copia. Funziona su Instagram, PUBG, Free Fire, TikTok, WhatsApp e ovunque.' },
            { question: 'Come fare un nome stiloso per PUBG e Free Fire?', answer: 'Scrivi il tuo nome sopra, scorri gli stili e tocca quello che ti piace — si copia all\'istante.' },
            { question: 'Questo generatore è gratuito?', answer: 'Totalmente gratuito! Nessuna registrazione, nessun download, nessun limite.' },
        ],
    },

    tr: {
        content: `<p>Bir <strong>şık isim oluşturucu</strong> mu arıyorsunuz? Doğru yerdesiniz! Ücretsiz aracımız havalı fontlar, semboller ve benzersiz dekorasyonlarla <strong>şık isim tasarımları</strong> oluşturur. İsminizi yazın, bir stil seçin ve kopyalayın — bu kadar! <strong>Instagram, PUBG, Free Fire, TikTok, WhatsApp, Facebook</strong> ve tüm uygulamalarda çalışır.</p>
<h3>🎮 Oyun İçin Şık İsimler</h3>
<p><strong>Oyun isim oluşturucumuz</strong> oyuncular için yapıldı. <strong>PUBG şık isim</strong> veya <strong>Free Fire şık isim</strong> oluşturun. <strong>BGMI</strong>, Fortnite, COD Mobile ve Roblox da desteklenir.</p>
<h3>📱 Sosyal Medya İçin Şık İsimler</h3>
<p>Profilinizi benzersiz bir <strong>Instagram şık isim</strong> ile öne çıkarın. <strong>TikTok</strong>, <strong>WhatsApp</strong>, <strong>Facebook</strong> ve <strong>Discord</strong> için de geçerli.</p>
<h3>🛠️ Nasıl Çalışır</h3>
<p><strong>Şık metin oluşturucumuz</strong> Unicode karakterler kullanır — resim değil gerçek karakterler. Her yerde çalışır. 1000+ tasarım.</p>`,
        faqItems: [
            { question: 'Şık isim oluşturucu nedir?', answer: 'Metninizi özel Unicode fontlar ve sembollerle havalı isimlere dönüştüren bir araç. Yazın, seçin, kopyalayın. Instagram, PUBG, Free Fire, TikTok, WhatsApp ve her yerde çalışır.' },
            { question: 'PUBG ve Free Fire için şık isim nasıl yapılır?', answer: 'Yukarıya isminizi yazın, stilleri kaydırın ve beğendiğinize dokunun — anında kopyalanır. Oyun içi isim olarak yapıştırın.' },
            { question: 'Bu oluşturucu ücretsiz mi?', answer: 'Tamamen ücretsiz! Kayıt, indirme veya sınır yok.' },
        ],
    },

    ar: {
        content: `<p>تبحث عن <strong>مولد أسماء أنيقة</strong>؟ أنت في المكان الصحيح! أداتنا المجانية تنشئ <strong>تصاميم أسماء أنيقة</strong> بخطوط رائعة ورموز وزخارف فريدة. اكتب اسمك، اختر نمط وانسخ — هذا كل شيء! تعمل على <strong>إنستغرام، ببجي، فري فاير، تيك توك، واتساب، فيسبوك</strong> وكل التطبيقات.</p>
<h3>🎮 أسماء أنيقة للألعاب</h3>
<p><strong>مولد أسماء الألعاب</strong> مصمم للاعبين. أنشئ <strong>اسم ببجي أنيق</strong> أو <strong>اسم فري فاير أنيق</strong>. أيضاً <strong>BGMI</strong> وفورتنايت وكول أوف ديوتي وروبلوكس.</p>
<h3>📱 أسماء أنيقة لوسائل التواصل</h3>
<p>اجعل بروفايلك مميزاً بـ<strong>اسم إنستغرام أنيق</strong> فريد. أيضاً لـ<strong>تيك توك</strong> و<strong>واتساب</strong> و<strong>فيسبوك</strong> و<strong>ديسكورد</strong>.</p>
<h3>🛠️ كيف يعمل</h3>
<p><strong>مولد النص الأنيق</strong> يستخدم أحرف Unicode — أحرف حقيقية وليست صور. تعمل في كل مكان. أكثر من 1000 تصميم.</p>`,
        faqItems: [
            { question: 'ما هو مولد الأسماء الأنيقة؟', answer: 'أداة تحول نصك لأسماء رائعة بخطوط Unicode خاصة. اكتب، اختر، انسخ. يعمل على إنستغرام وببجي وفري فاير وتيك توك وواتساب وكل مكان.' },
            { question: 'كيف أصنع اسم أنيق لببجي وفري فاير؟', answer: 'اكتب اسمك أعلاه، مرر بين الأنماط واضغط على ما يعجبك — ينسخ فوراً. الصقه كاسم في اللعبة.' },
            { question: 'هل هذا المولد مجاني؟', answer: 'مجاني تماماً! بدون تسجيل، بدون تحميل، بدون حدود.' },
        ],
    },

    id: {
        content: `<p>Cari <strong>generator nama stylish</strong>? Kamu di tempat yang tepat! Tool gratis kami membuat <strong>desain nama stylish</strong> dengan font keren, simbol dan dekorasi unik. Ketik nama, pilih gaya dan salin — selesai! Bekerja di <strong>Instagram, PUBG, Free Fire, TikTok, WhatsApp, Facebook</strong> dan semua aplikasi.</p>
<h3>🎮 Nama Stylish untuk Gaming</h3>
<p><strong>Generator nama gaming</strong> kami dibuat untuk pemain. Buat <strong>nama PUBG stylish</strong> atau <strong>nama Free Fire stylish</strong>. Juga <strong>BGMI</strong>, Fortnite, COD Mobile dan Roblox.</p>
<h3>📱 Nama Stylish untuk Media Sosial</h3>
<p>Bikin profilmu unik dengan <strong>nama Instagram stylish</strong>. Juga untuk <strong>TikTok</strong>, <strong>WhatsApp</strong>, <strong>Facebook</strong> dan <strong>Discord</strong>.</p>
<h3>🛠️ Cara Kerja</h3>
<p><strong>Generator teks stylish</strong> kami pakai karakter Unicode — karakter asli bukan gambar. Bekerja di mana saja. Lebih dari 1000 desain.</p>`,
        faqItems: [
            { question: 'Apa itu generator nama stylish?', answer: 'Tool yang mengubah teks kamu jadi nama keren dengan font Unicode spesial. Ketik, pilih, salin. Bekerja di Instagram, PUBG, Free Fire, TikTok, WhatsApp dan di mana saja.' },
            { question: 'Cara buat nama stylish untuk PUBG dan Free Fire?', answer: 'Ketik nama di atas, scroll gaya dan tap yang kamu suka — langsung tersalin. Tempel sebagai nama in-game.' },
            { question: 'Apakah generator ini gratis?', answer: 'Sepenuhnya gratis! Tanpa daftar, tanpa download, tanpa batas.' },
        ],
    },

    ja: {
        content: `<p><strong>スタイリッシュ名前ジェネレーター</strong>をお探しですか？ここが正解です！無料ツールで<strong>スタイリッシュな名前デザイン</strong>をクールなフォント、シンボル、ユニークなデコレーションで作成できます。名前を入力、スタイルを選んでコピー — それだけ！<strong>Instagram、PUBG、Free Fire、TikTok、WhatsApp、Facebook</strong>とすべてのアプリで動作します。</p>
<h3>🎮 ゲーム用スタイリッシュ名前</h3>
<p><strong>ゲーム名ジェネレーター</strong>はプレイヤーのために作られました。<strong>PUBGスタイリッシュ名前</strong>や<strong>Free Fireスタイリッシュ名前</strong>を作成。<strong>BGMI</strong>、Fortnite、COD Mobile、Robloxもサポート。</p>
<h3>📱 SNS用スタイリッシュ名前</h3>
<p>ユニークな<strong>Instagramスタイリッシュ名前</strong>でプロフィールを目立たせましょう。<strong>TikTok</strong>、<strong>WhatsApp</strong>、<strong>Facebook</strong>、<strong>Discord</strong>にも対応。</p>
<h3>🛠️ 仕組み</h3>
<p><strong>スタイリッシュテキストジェネレーター</strong>はUnicode文字を使用 — 画像ではなく本物の文字。どこでも動作します。1000以上のデザイン。</p>`,
        faqItems: [
            { question: 'スタイリッシュ名前ジェネレーターとは？', answer: 'テキストを特別なUnicodeフォントとシンボルでクールな名前に変換するツール。入力、選択、コピー。Instagram、PUBG、Free Fire、TikTok、WhatsAppとどこでも動作します。' },
            { question: 'PUBGとFree Fireのスタイリッシュ名前の作り方は？', answer: '上に名前を入力、スタイルをスクロールして好きなものをタップ — 即座にコピーされます。ゲーム内の名前として貼り付け。' },
            { question: 'このジェネレーターは無料ですか？', answer: '完全無料！登録、ダウンロード、制限なし。' },
        ],
    },

    nl: {
        content: `<p>Op zoek naar een <strong>stijlvolle naamgenerator</strong>? Je bent op de juiste plek! Onze gratis tool maakt <strong>stijlvolle naamontwerpen</strong> met coole lettertypen, symbolen en unieke decoraties. Typ je naam, kies een stijl en kopieer — klaar! Werkt op <strong>Instagram, PUBG, Free Fire, TikTok, WhatsApp, Facebook</strong> en alle andere apps.</p>
<h3>🎮 Stijlvolle Gaming-Namen</h3>
<p>Onze <strong>gaming-naamgenerator</strong> is gemaakt voor gamers. Maak een <strong>PUBG stijlvolle naam</strong> of <strong>Free Fire stijlvolle naam</strong>. Ook <strong>BGMI</strong>, Fortnite, COD Mobile en Roblox.</p>
<h3>📱 Stijlvolle Namen voor Social Media</h3>
<p>Laat je profiel opvallen met een unieke <strong>Instagram stijlvolle naam</strong>. Ook voor <strong>TikTok</strong>, <strong>WhatsApp</strong>, <strong>Facebook</strong> en <strong>Discord</strong>.</p>
<h3>🛠️ Hoe Het Werkt</h3>
<p>Onze <strong>stijlvolle tekstgenerator</strong> gebruikt Unicode-tekens — echte tekens, geen afbeeldingen. Werkt overal. 1000+ ontwerpen.</p>`,
        faqItems: [
            { question: 'Wat is een stijlvolle naamgenerator?', answer: 'Een tool die je tekst omzet in coole namen met speciale Unicode-lettertypen en symbolen. Typ, kies, kopieer. Werkt op Instagram, PUBG, Free Fire, TikTok, WhatsApp en overal.' },
            { question: 'Hoe maak ik een stijlvolle PUBG- of Free Fire-naam?', answer: 'Typ je naam hierboven, scroll door de stijlen en tik op degene die je leuk vindt — wordt direct gekopieerd.' },
            { question: 'Is deze generator gratis?', answer: 'Helemaal gratis! Geen registratie, downloads of limieten.' },
        ],
    },
};

export function getHomepageSEO(locale: Locale): HomepageSEO {
    return homepageSEOContent[locale] || homepageSEOContent.en;
}
