// Pre-built ready-to-copy stylish names organized by category
// These are curated Unicode names users can browse and copy instantly

export interface PreBuiltName {
    name: string;
    style: string; // short style label
}

export interface PreBuiltCategory {
    slug: string;
    names: PreBuiltName[];
}

export const preBuiltNames: Record<string, PreBuiltName[]> = {
    gaming: [
        { name: '꧁༒☬𝓓𝓪𝓻𝓴𝓚𝓷𝓲𝓰𝓱𝓽☬༒꧂', style: 'Dark Knight' },
        { name: '꧁★彡[ᴅᴇᴀᴅ ꜱʜᴏᴛ]彡★꧂', style: 'Dead Shot' },
        { name: '⚡𝕊𝕙𝕒𝕕𝕠𝕨 𝔸𝕤𝕤𝕒𝕤𝕤𝕚𝕟⚡', style: 'Shadow Assassin' },
        { name: '☠️𝙏𝙤𝙭𝙞𝙘 𝙑𝙞𝙥𝙚𝙧☠️', style: 'Toxic Viper' },
        { name: '꧁⁣༒𝑷𝒉𝒂𝒏𝒕𝒐𝒎 𝑹𝒆𝒂𝒑𝒆𝒓༒꧂', style: 'Phantom Reaper' },
        { name: '★彡 ᴺᴵᴳᴴᵀ ᴴᴬᵂᴷ 彡★', style: 'Night Hawk' },
        { name: '╰‿╯𝕃𝕖𝕘𝕖𝕟𝕕 𝕂𝕚𝕝𝕝𝕖𝕣╰‿╯', style: 'Legend Killer' },
        { name: '꧁ঔৣ☬𝗕𝗹𝗮𝘇𝗲 𝗦𝘁𝗼𝗿𝗺☬ঔৣ꧂', style: 'Blaze Storm' },
        { name: '乂❤‿❤乂 𝕊𝕟𝕚𝕡𝕖𝕣 𝕂𝕚𝕟𝕘', style: 'Sniper King' },
        { name: '꧁☆☬ 𝓦𝓪𝓻 𝓜𝓪𝓬𝓱𝓲𝓷𝓮 ☬☆꧂', style: 'War Machine' },
        { name: '☬ᴴᴱᴬᴰˢᴴᴼᵀ ᴳᴼᴰ☬', style: 'Headshot God' },
        { name: '꧁༺₦ɨ₦ℑ₳꧂', style: 'Ninja' },
        { name: '⫷ 𝕊𝕥𝕠𝕣𝕞 𝔹𝕣𝕖𝕒𝕜𝕖𝕣 ⫸', style: 'Storm Breaker' },
        { name: '✰𝙱𝚞𝚕𝚕𝚎𝚝 𝙿𝚛𝚘𝚘𝚏✰', style: 'Bullet Proof' },
        { name: '꧁★ 𝕯𝖆𝖗𝖐 𝕬𝖓𝖌𝖊𝖑 ★꧂', style: 'Dark Angel' },
        { name: '╾━╤デ╦︻ 𝓢𝓷𝓲𝓹𝓮𝓻', style: 'Sniper' },
        { name: '꧁ᴳᵒᵈ 𝗢𝗳 𝗪𝗮𝗿꧂', style: 'God Of War' },
        { name: '☢️𝙍𝙖𝙙𝙞𝙤𝙖𝙘𝙩𝙞𝙫𝙚☢️', style: 'Radioactive' },
        { name: '꧁༒☬𝔇𝔢𝔪𝔬𝔫☬༒꧂', style: 'Demon' },
        { name: '⚔️𝕭𝖊𝖗𝖘𝖊𝖗𝖐𝖊𝖗⚔️', style: 'Berserker' },
    ],

    boy: [
        { name: '꧁𝓚𝓲𝓷𝓰 𝓞𝓯 𝓢𝓽𝔂𝓵𝓮꧂', style: 'King Of Style' },
        { name: '✦𝙱𝚊𝚍 𝙱𝚘𝚢 ✦', style: 'Bad Boy' },
        { name: '꧁★𝕽𝖔𝖞𝖆𝖑 𝕶𝖎𝖓𝖌★꧂', style: 'Royal King' },
        { name: '⚡𝙰𝚕𝚙𝚑𝚊 𝙼𝚊𝚕𝚎⚡', style: 'Alpha Male' },
        { name: '♛𝒟𝒶𝓇𝓀 𝒫𝓇𝒾𝓃𝒸𝑒♛', style: 'Dark Prince' },
        { name: '꧁ 𝕃𝕠𝕟𝕖 𝕎𝕠𝕝𝕗 ꧂', style: 'Lone Wolf' },
        { name: '☬𝕳𝖊𝖆𝖗𝖙𝖑𝖊𝖘𝖘 𝕭𝖔𝖞☬', style: 'Heartless Boy' },
        { name: '★彡𝕊𝕥𝕪𝕝𝕚𝕤𝕙 𝔹𝕠𝕪彡★', style: 'Stylish Boy' },
        { name: '꧁ঔৣ☬𝓡𝓮𝓫𝓮𝓵☬ঔৣ꧂', style: 'Rebel' },
        { name: '♔ꜱɪʟᴇɴᴛ ᴋɪʟʟᴇʀ♔', style: 'Silent Killer' },
        { name: '꧁✿𝓐𝓽𝓽𝓲𝓽𝓾𝓭𝓮 𝓑𝓸𝔂✿꧂', style: 'Attitude Boy' },
        { name: '⫷𝙷𝚞𝚗𝚝𝚎𝚛⫸', style: 'Hunter' },
        { name: '꧁ᴮᴼˢˢ ᴮᴼʸ꧂', style: 'Boss Boy' },
        { name: '✰𝐒𝐚𝐯𝐚𝐠𝐞 𝐊𝐢𝐧𝐠✰', style: 'Savage King' },
        { name: '꧁♚𝕯𝖆𝖗𝖐 𝕷𝖔𝖗𝖉♚꧂', style: 'Dark Lord' },
    ],

    girl: [
        { name: '꧁💖𝒫𝓇𝒾𝓃𝒸𝑒𝓈𝓈💖꧂', style: 'Princess' },
        { name: '✿𝓠𝓾𝓮𝓮𝓷 𝓞𝓯 𝓗𝓮𝓪𝓻𝓽𝓼✿', style: 'Queen Of Hearts' },
        { name: '🦋𝔹𝕦𝕥𝕥𝕖𝕣𝕗𝕝𝕪 𝔾𝕚𝕣𝕝🦋', style: 'Butterfly Girl' },
        { name: '♡𝕊𝕨𝕖𝕖𝕥 𝔸𝕟𝕘𝕖𝕝♡', style: 'Sweet Angel' },
        { name: '꧁🌸𝓒𝓾𝓽𝓮 𝓓𝓸𝓵𝓵🌸꧂', style: 'Cute Doll' },
        { name: '✦𝙱𝚊𝚋𝚢 𝙶𝚒𝚛𝚕✦', style: 'Baby Girl' },
        { name: '👑𝒬𝓊𝑒𝑒𝓃 𝐵𝑒𝑒👑', style: 'Queen Bee' },
        { name: '꧁💫𝕊𝕥𝕒𝕣 𝔾𝕚𝕣𝕝💫꧂', style: 'Star Girl' },
        { name: '🌹𝓡𝓸𝓼𝓮 𝓟𝓻𝓲𝓷𝓬𝓮𝓼𝓼🌹', style: 'Rose Princess' },
        { name: '♡ᴅʀᴇᴀᴍ ɢɪʀʟ♡', style: 'Dream Girl' },
        { name: '꧁☆𝙶𝚕𝚊𝚖 𝙶𝚒𝚛𝚕☆꧂', style: 'Glam Girl' },
        { name: '✰𝓐𝓷𝓰𝓮𝓵 𝓔𝔂𝓮𝓼✰', style: 'Angel Eyes' },
        { name: '🌺𝕃𝕠𝕧𝕖𝕝𝕪 𝔾𝕚𝕣𝕝🌺', style: 'Lovely Girl' },
        { name: '꧁♡𝒫𝒾𝓃𝓀 𝒫𝓇𝒾𝓃𝒸𝑒𝓈𝓈♡꧂', style: 'Pink Princess' },
        { name: '💎𝕯𝖎𝖆𝖒𝖔𝖓𝖉 𝕲𝖎𝖗𝖑💎', style: 'Diamond Girl' },
    ],

    beautiful: [
        { name: '꧁✨𝓑𝓮𝓪𝓾𝓽𝓲𝓯𝓾𝓵 𝓢𝓸𝓾𝓵✨꧂', style: 'Beautiful Soul' },
        { name: '🌟𝔹𝕖𝕒𝕦𝕥𝕚𝕗𝕦𝕝 𝔻𝕣𝕖𝕒𝕞🌟', style: 'Beautiful Dream' },
        { name: '✿𝒢𝑜𝓁𝒹𝑒𝓃 𝐻𝑒𝒶𝓇𝓉✿', style: 'Golden Heart' },
        { name: '꧁🌸𝕊𝕦𝕟𝕤𝕙𝕚𝕟𝕖🌸꧂', style: 'Sunshine' },
        { name: '💫𝓢𝓹𝓪𝓻𝓴𝓵𝓮 𝓢𝓽𝓪𝓻💫', style: 'Sparkle Star' },
        { name: '🌹𝙱𝚎𝚊𝚞𝚝𝚒𝚏𝚞𝚕 𝙼𝚒𝚗𝚍🌹', style: 'Beautiful Mind' },
        { name: '✦𝕊𝕥𝕒𝕣𝕕𝕦𝕤𝕥✦', style: 'Stardust' },
        { name: '꧁♡𝓟𝓾𝓻𝓮 𝓗𝓮𝓪𝓻𝓽♡꧂', style: 'Pure Heart' },
        { name: '🦋𝔾𝕣𝕒𝕔𝕖𝕗𝕦𝕝🦋', style: 'Graceful' },
        { name: '💖𝓑𝓮𝓪𝓾𝓽𝔂 𝓠𝓾𝓮𝓮𝓷💖', style: 'Beauty Queen' },
        { name: '✰𝕄𝕠𝕠𝕟𝕝𝕚𝕘𝕙𝕥✰', style: 'Moonlight' },
        { name: '꧁🌺𝙴𝚕𝚎𝚐𝚊𝚗𝚝 𝙱𝚎𝚊𝚞𝚝𝚢🌺꧂', style: 'Elegant Beauty' },
    ],

    couple: [
        { name: '♡𝓚𝓲𝓷𝓰 & 𝓠𝓾𝓮𝓮𝓷♡', style: 'King & Queen' },
        { name: '꧁💑𝕃𝕠𝕧𝕖 𝔹𝕚𝕣𝕕𝕤꧂', style: 'Love Birds' },
        { name: '💕𝒮𝑜𝓊𝓁 𝑀𝒶𝓉𝑒𝓈💕', style: 'Soul Mates' },
        { name: '♚𝙷𝚒𝚜 𝚀𝚞𝚎𝚎𝚗♛', style: 'His Queen' },
        { name: '♛𝙷𝚎𝚛 𝙺𝚒𝚗𝚐♚', style: 'Her King' },
        { name: '꧁❤️𝓕𝓸𝓻𝓮𝓿𝓮𝓻 𝓣𝓸𝓰𝓮𝓽𝓱𝓮𝓻❤️꧂', style: 'Forever Together' },
        { name: '🌹𝕎𝕚𝕗𝕖𝕪🌹', style: 'Wifey' },
        { name: '💍𝕳𝖚𝖇𝖇𝖞💍', style: 'Hubby' },
        { name: '♡𝙱𝚊𝚋𝚢 & 𝙱𝚘𝚘♡', style: 'Baby & Boo' },
        { name: '꧁💞𝓜𝔂 𝓛𝓸𝓿𝓮💞꧂', style: 'My Love' },
        { name: '✦𝕊𝕨𝕖𝕖𝕥 ℂ𝕠𝕦𝕡𝕝𝕖✦', style: 'Sweet Couple' },
        { name: '❤️‍🔥𝙱𝚘𝚗𝚗𝚒𝚎 & 𝙲𝚕𝚢𝚍𝚎❤️‍🔥', style: 'Bonnie & Clyde' },
    ],

    'group-name': [
        { name: '꧁⚡𝕋𝕙𝕖 𝕃𝕖𝕘𝕖𝕟𝕕𝕤⚡꧂', style: 'The Legends' },
        { name: '★彡𝓢𝓺𝓾𝓪𝓭 𝓖𝓸𝓪𝓵𝓼彡★', style: 'Squad Goals' },
        { name: '꧁☬𝕯𝖆𝖗𝖐 𝕬𝖗𝖒𝖞☬꧂', style: 'Dark Army' },
        { name: '⚔️𝙱𝚛𝚘𝚝𝚑𝚎𝚛𝚑𝚘𝚘𝚍⚔️', style: 'Brotherhood' },
        { name: '👑𝓡𝓸𝔂𝓪𝓵 𝓕𝓪𝓶𝓲𝓵𝔂👑', style: 'Royal Family' },
        { name: '꧁💫𝔹𝕖𝕤𝕥 𝔽𝕣𝕚𝕖𝕟𝕕𝕤💫꧂', style: 'Best Friends' },
        { name: '🔥𝙵𝚒𝚛𝚎 𝚂𝚚𝚞𝚊𝚍🔥', style: 'Fire Squad' },
        { name: '꧁♚𝕶𝖎𝖓𝖌𝖘 𝖔𝖋 𝕲𝖆𝖒𝖎𝖓𝖌♚꧂', style: 'Kings of Gaming' },
        { name: '✰𝕊𝕥𝕒𝕣 𝕋𝕖𝕒𝕞✰', style: 'Star Team' },
        { name: '꧁★𝓣𝓱𝓮 𝓐𝓿𝓮𝓷𝓰𝓮𝓻𝓼★꧂', style: 'The Avengers' },
        { name: '⫷𝙴𝚕𝚒𝚝𝚎 𝙲𝚕𝚊𝚗⫸', style: 'Elite Clan' },
        { name: '꧁🔱𝕿𝖍𝖊 𝕲𝖆𝖓𝖌🔱꧂', style: 'The Gang' },
    ],

    mafia: [
        { name: '꧁☬𝕸𝖆𝖋𝖎𝖆 𝕭𝖔𝖘𝖘☬꧂', style: 'Mafia Boss' },
        { name: '🔫𝓖𝓪𝓷𝓰𝓼𝓽𝓮𝓻🔫', style: 'Gangster' },
        { name: '꧁⚔️𝕯𝖔𝖓 𝕮𝖔𝖗𝖑𝖊𝖔𝖓𝖊⚔️꧂', style: 'Don Corleone' },
        { name: '☠️𝙳𝚊𝚛𝚔 𝙼𝚊𝚏𝚒𝚊☠️', style: 'Dark Mafia' },
        { name: '꧁💀𝕿𝖍𝖊 𝕲𝖔𝖉𝖋𝖆𝖙𝖍𝖊𝖗💀꧂', style: 'The Godfather' },
        { name: '🗡️𝕊𝕚𝕝𝕖𝕟𝕥 𝕄𝕒𝕗𝕚𝕒🗡️', style: 'Silent Mafia' },
        { name: '꧁☬𝓓𝓸𝓷 𝓑𝓸𝓼𝓼☬꧂', style: 'Don Boss' },
        { name: '⚡𝙼𝚊𝚏𝚒𝚊 𝙺𝚒𝚗𝚐⚡', style: 'Mafia King' },
        { name: '꧁🔥𝕋𝕙𝕖 𝕄𝕠𝕓🔥꧂', style: 'The Mob' },
        { name: '💣𝓣𝓱𝓮 𝓓𝓸𝓷💣', style: 'The Don' },
        { name: '꧁♠️𝕯𝖊𝖆𝖙𝖍 𝕸𝖆𝖋𝖎𝖆♠️꧂', style: 'Death Mafia' },
        { name: '🖤𝕸𝖆𝖋𝖎𝖆 𝕷𝖔𝖗𝖉🖤', style: 'Mafia Lord' },
    ],

    wifi: [
        { name: '꧁📶𝓝𝓸 𝓕𝓻𝓮𝓮 𝓦𝓲𝓕𝓲꧂', style: 'No Free WiFi' },
        { name: '🔒𝕋𝕣𝕪 𝔸𝕘𝕒𝕚𝕟 𝕃𝕒𝕥𝕖𝕣', style: 'Try Again Later' },
        { name: '꧁💀𝙿𝚊𝚜𝚜𝚠𝚘𝚛𝚍 𝙸𝚜 𝟷𝟸𝟹𝟺💀꧂', style: 'Password 1234' },
        { name: '⚡𝕱𝖆𝖘𝖙 𝖂𝖎𝕱𝖎⚡', style: 'Fast WiFi' },
        { name: '꧁😂𝓝𝓸𝓽 𝓨𝓸𝓾𝓻 𝓦𝓲𝓕𝓲😂꧂', style: 'Not Your WiFi' },
        { name: '🛜𝕃𝕠𝕒𝕕𝕚𝕟𝕘...', style: 'Loading...' },
        { name: '꧁🔐𝙿𝚊𝚢 𝙵𝚘𝚛 𝚆𝚒𝙵𝚒🔐꧂', style: 'Pay For WiFi' },
        { name: '☠️𝕍𝕚𝕣𝕦𝕤 𝕀𝕟𝕤𝕚𝕕𝕖☠️', style: 'Virus Inside' },
        { name: '꧁🤷𝓖𝓾𝓮𝓼𝓼 𝓣𝓱𝓮 𝓟𝓪𝓼𝓼🤷꧂', style: 'Guess The Pass' },
        { name: '📵𝙽𝚘 𝙸𝚗𝚝𝚎𝚛𝚗𝚎𝚝📵', style: 'No Internet' },
        { name: '꧁✨𝕊𝕥𝕪𝕝𝕚𝕤𝕙 𝕎𝕚𝔽𝕚✨꧂', style: 'Stylish WiFi' },
        { name: '🔥𝕳𝖔𝖙𝖘𝖕𝖔𝖙 𝕶𝖎𝖓𝖌🔥', style: 'Hotspot King' },
    ],

    pubg: [
        { name: '꧁༒☬𝓗𝓮𝓪𝓭𝓱𝓾𝓷𝓽𝓮𝓻☬༒꧂', style: 'Headhunter' },
        { name: '⚡𝕊𝕟𝕚𝕡𝕖𝕣 𝔼𝕝𝕚𝕥𝕖⚡', style: 'Sniper Elite' },
        { name: '꧁★𝙿𝚄𝙱𝙶 𝙺𝚒𝚗𝚐★꧂', style: 'PUBG King' },
        { name: '☬ᴄʜɪᴄᴋᴇɴ ᴅɪɴɴᴇʀ☬', style: 'Chicken Dinner' },
        { name: '꧁⚔️𝕭𝖆𝖙𝖙𝖑𝖊 𝕲𝖔𝖉⚔️꧂', style: 'Battle God' },
        { name: '╾━╤デ╦︻ 𝙰𝚆𝙼 𝙶𝚘𝚍', style: 'AWM God' },
        { name: '꧁ᴴᴱᴬᴰˢᴴᴼᵀ ᴹᴬᶜᴴᴵᴺᴱ꧂', style: 'Headshot Machine' },
        { name: '🎯𝕊𝕢𝕦𝕒𝕕 𝕃𝕖𝕒𝕕𝕖𝕣🎯', style: 'Squad Leader' },
        { name: '꧁☠️𝓓𝓮𝓪𝓽𝓱 𝓓𝓮𝓪𝓵𝓮𝓻☠️꧂', style: 'Death Dealer' },
        { name: '⫷𝕃𝕠𝕠𝕥 𝕂𝕚𝕟𝕘⫸', style: 'Loot King' },
        { name: '꧁🔥𝙷𝚘𝚝 𝙳𝚛𝚘𝚙𝚙𝚎𝚛🔥꧂', style: 'Hot Dropper' },
        { name: '☬𝕲𝖗𝖎𝖑𝖑 𝕸𝖆𝖘𝖙𝖊𝖗☬', style: 'Grill Master' },
        { name: '꧁✰𝓟𝓪𝓷 𝓦𝓪𝓻𝓻𝓲𝓸𝓻✰꧂', style: 'Pan Warrior' },
        { name: '⚡𝕄𝟜 𝔹𝕖𝕒𝕤𝕥⚡', style: 'M4 Beast' },
        { name: '꧁💀𝙱𝚘𝚗𝚎 𝙲𝚛𝚞𝚜𝚑𝚎𝚛💀꧂', style: 'Bone Crusher' },
        { name: '🏆𝕮𝖔𝖓𝖖𝖚𝖊𝖗𝖔𝖗🏆', style: 'Conqueror' },
        { name: '꧁⫷𝓢𝓽𝓮𝓪𝓵𝓽𝓱 𝓚𝓲𝓵𝓵𝓮𝓻⫸꧂', style: 'Stealth Killer' },
        { name: '☢️𝕎𝕒𝕣 𝔽𝕣𝕖𝕒𝕜☢️', style: 'War Freak' },
        { name: '꧁🎮𝙿𝚛𝚘 𝙿𝚕𝚊𝚢𝚎𝚛🎮꧂', style: 'Pro Player' },
        { name: '♛𝕽𝖔𝖞𝖆𝖑 𝕰𝖑𝖎𝖙𝖊♛', style: 'Royal Elite' },
    ],

    'free-fire': [
        { name: '꧁🔥𝓕𝓲𝓻𝓮 𝓓𝓮𝓶𝓸𝓷🔥꧂', style: 'Fire Demon' },
        { name: '⚡𝕳𝖊𝖆𝖉𝖘𝖍𝖔𝖙 𝕶𝖎𝖓𝖌⚡', style: 'FF Headshot King' },
        { name: '꧁★𝙵𝙵 𝙶𝚘𝚍★꧂', style: 'FF God' },
        { name: '☬ᴮᴼᴵᴸᴱᴰ ᴬᴸᴼᴼ☬', style: 'Boiled Aloo' },
        { name: '꧁💀𝕊𝕜𝕦𝕝𝕝 𝕋𝕣𝕠𝕠𝕡𝕖𝕣💀꧂', style: 'Skull Trooper' },
        { name: '🔫𝓞𝓷𝓮 𝓣𝓪𝓹 𝓚𝓲𝓷𝓰🔫', style: 'One Tap King' },
        { name: '꧁⚔️𝕭𝖑𝖆𝖉𝖊 𝕸𝖆𝖘𝖙𝖊𝖗⚔️꧂', style: 'Blade Master' },
        { name: '🎯𝙳𝚎𝚜𝚒 𝙶𝚊𝚖𝚎𝚛🎯', style: 'Desi Gamer' },
        { name: '꧁🔥𝓑𝓾𝓻𝓷𝓲𝓷𝓰 𝓕𝓾𝓻𝔂🔥꧂', style: 'Burning Fury' },
        { name: '☠️𝕋𝕠𝕩𝕚𝕔 𝕂𝕚𝕟𝕘☠️', style: 'Toxic King' },
        { name: '꧁⫷𝕱𝖎𝖗𝖊 𝕾𝖙𝖔𝖗𝖒⫸꧂', style: 'Fire Storm' },
        { name: '💥𝙱𝚘𝚘𝚖 𝙱𝚘𝚘𝚖💥', style: 'Boom Boom' },
        { name: '꧁🏆𝓖𝓻𝓪𝓷𝓭 𝓜𝓪𝓼𝓽𝓮𝓻🏆꧂', style: 'Grand Master' },
        { name: '⚡𝕊𝕡𝕖𝕖𝕕 𝕂𝕚𝕝𝕝⚡', style: 'Speed Kill' },
        { name: '꧁★𝙵𝚛𝚎𝚎 𝙵𝚒𝚛𝚎 𝙱𝚘𝚜𝚜★꧂', style: 'Free Fire Boss' },
        { name: '☬𝕯𝖊𝖘𝖙𝖗𝖔𝖞𝖊𝖗☬', style: 'Destroyer' },
        { name: '꧁🎮𝓔𝓵𝓲𝓽𝓮 𝓢𝓺𝓾𝓪𝓭🎮꧂', style: 'Elite Squad' },
        { name: '💀𝕊𝕙𝕒𝕕𝕠𝕨 𝔽𝕚𝕘𝕙𝕥𝕖𝕣💀', style: 'Shadow Fighter' },
    ],

    instagram: [
        { name: '✨𝒜𝑒𝓈𝓉𝒽𝑒𝓉𝒾𝒸 𝒱𝒾𝒷𝑒𝓈✨', style: 'Aesthetic Vibes' },
        { name: '🌸𝕊𝕠𝕗𝕥 𝔾𝕚𝕣𝕝 𝔼𝕣𝕒🌸', style: 'Soft Girl Era' },
        { name: '♡𝓛𝓲𝓿𝓲𝓷𝓰 𝓜𝔂 𝓑𝓮𝓼𝓽 𝓛𝓲𝓯𝓮♡', style: 'Best Life' },
        { name: '👑𝙱𝚘𝚜𝚜 𝙱𝚊𝚋𝚎👑', style: 'Boss Babe' },
        { name: '🦋𝕄𝕒𝕚𝕟 ℂ𝕙𝕒𝕣𝕒𝕔𝕥𝕖𝕣🦋', style: 'Main Character' },
        { name: '✰𝓥𝓲𝓫𝓮 𝓒𝓱𝓮𝓬𝓴✰', style: 'Vibe Check' },
        { name: '💫𝕊𝕥𝕒𝕣 𝔾𝕚𝕣𝕝💫', style: 'IG Star Girl' },
        { name: '🤍𝙼𝚒𝚗𝚒𝚖𝚊𝚕𝚒𝚜𝚝🤍', style: 'Minimalist' },
        { name: '🌙𝓜𝓸𝓸𝓷 𝓒𝓱𝓲𝓵𝓭🌙', style: 'Moon Child' },
        { name: '💅𝕋𝕙𝕒𝕥 𝔾𝕚𝕣𝕝💅', style: 'That Girl' },
        { name: '☀️𝒮𝓊𝓃𝓈𝒽𝒾𝓃𝑒 𝒮𝓉𝒶𝓉𝑒☀️', style: 'Sunshine State' },
        { name: '🌹𝕯𝖆𝖗𝖐 𝕬𝖊𝖘𝖙𝖍𝖊𝖙𝖎𝖈🌹', style: 'Dark Aesthetic' },
        { name: '✦𝙶𝚕𝚘𝚠 𝚄𝚙✦', style: 'Glow Up' },
        { name: '💎𝓛𝓾𝔁𝓾𝓻𝔂 𝓛𝓲𝓯𝓮💎', style: 'Luxury Life' },
        { name: '🔥𝕀𝕔𝕠𝕟𝕚𝕔🔥', style: 'Iconic' },
    ],

    tiktok: [
        { name: '🎵𝓣𝓲𝓴𝓣𝓸𝓴 𝓢𝓽𝓪𝓻🎵', style: 'TikTok Star' },
        { name: '💃𝕍𝕚𝕣𝕒𝕝 𝕂𝕚𝕟𝕘💃', style: 'Viral King' },
        { name: '✨𝙲𝚘𝚗𝚝𝚎𝚗𝚝 𝙲𝚛𝚎𝚊𝚝𝚘𝚛✨', style: 'Content Creator' },
        { name: '🎬𝕊𝕔𝕖𝕟𝕖 𝕊𝕥𝕖𝕒𝕝𝕖𝕣🎬', style: 'Scene Stealer' },
        { name: '💫𝓣𝓻𝓮𝓷𝓭 𝓢𝓮𝓽𝓽𝓮𝓻💫', style: 'Trend Setter' },
        { name: '🎤𝕍𝕠𝕚𝕔𝕖 𝕆𝕧𝕖𝕣 𝕂𝕚𝕟𝕘🎤', style: 'VoiceOver King' },
        { name: '😎𝙵𝚈𝙿 𝙺𝚒𝚗𝚐😎', style: 'FYP King' },
        { name: '🌟𝓓𝓾𝓮𝓽 𝓜𝓮🌟', style: 'Duet Me' },
        { name: '🔥𝕍𝕚𝕣𝕒𝕝 𝕍𝕚𝕓𝕖𝕤🔥', style: 'Viral Vibes' },
        { name: '✰𝙳𝚊𝚗𝚌𝚎 𝙼𝚊𝚌𝚑𝚒𝚗𝚎✰', style: 'Dance Machine' },
        { name: '💥𝓢𝓴𝓲𝓽 𝓚𝓲𝓷𝓰💥', style: 'Skit King' },
        { name: '🎯𝕋𝕣𝕖𝕟𝕕𝕚𝕟𝕘 ℕ𝕠𝕨🎯', style: 'Trending Now' },
    ],

    whatsapp: [
        { name: '💬𝓢𝓽𝔂𝓵𝓲𝓼𝓱 𝓢𝓽𝓪𝓽𝓾𝓼💬', style: 'Stylish Status' },
        { name: '🚫𝕃𝕒𝕤𝕥 𝕊𝕖𝕖𝕟 ℕ𝕖𝕧𝕖𝕣🚫', style: 'Last Seen Never' },
        { name: '😏𝙰𝚝𝚝𝚒𝚝𝚞𝚍𝚎 𝙺𝚒𝚗𝚐😏', style: 'Attitude King' },
        { name: '♡𝓛𝓸𝓿𝓮 𝓨𝓸𝓾𝓻𝓼𝓮𝓵𝓯♡', style: 'Love Yourself' },
        { name: '👑𝕂𝕚𝕟𝕘 𝕆𝕗 𝕊𝕥𝕒𝕥𝕦𝕤👑', style: 'King Of Status' },
        { name: '🌙𝙳𝚛𝚎𝚊𝚖𝚎𝚛🌙', style: 'Dreamer' },
        { name: '🔥𝓞𝓷 𝓕𝓲𝓻𝓮🔥', style: 'On Fire' },
        { name: '💪𝕊𝕖𝕝𝕗 𝕄𝕒𝕕𝕖💪', style: 'Self Made' },
        { name: '✨𝙱𝚕𝚎𝚜𝚜𝚎𝚍✨', style: 'Blessed' },
        { name: '😈𝓓𝓮𝓿𝓲𝓵 𝓘𝓷𝓼𝓲𝓭𝓮😈', style: 'Devil Inside' },
        { name: '🤘𝕊𝕒𝕧𝕒𝕘𝕖 𝕄𝕠𝕕𝕖🤘', style: 'Savage Mode' },
        { name: '💯𝙺𝚎𝚎𝚙 𝙸𝚝 𝚁𝚎𝚊𝚕💯', style: 'Keep It Real' },
    ],

    roblox: [
        { name: '🧱𝓑𝓵𝓸𝔁 𝓜𝓪𝓼𝓽𝓮𝓻🧱', style: 'Blox Master' },
        { name: '⚡𝕆𝕓𝕓𝕪 𝔾𝕠𝕕⚡', style: 'Obby God' },
        { name: '꧁🎮𝙶𝚊𝚖𝚎 𝙲𝚛𝚎𝚊𝚝𝚘𝚛🎮꧂', style: 'Game Creator' },
        { name: '💰𝕽𝖔𝖇𝖚𝖝 𝕶𝖎𝖓𝖌💰', style: 'Robux King' },
        { name: '🏰𝓣𝓸𝔀𝓮𝓻 𝓓𝓮𝓯𝓮𝓷𝓭𝓮𝓻🏰', style: 'Tower Defender' },
        { name: '🎯𝕊𝕙𝕒𝕣𝕜 𝔹𝕚𝕥𝕖🎯', style: 'Shark Bite' },
        { name: '⚔️𝙲𝚘𝚖𝚋𝚊𝚝 𝙿𝚛𝚘⚔️', style: 'Combat Pro' },
        { name: '🌟𝓐𝓭𝓸𝓹𝓽 𝓜𝓮 𝓢𝓽𝓪𝓻🌟', style: 'Adopt Me Star' },
        { name: '🔥𝕊𝕡𝕖𝕖𝕕 ℝ𝕦𝕟🔥', style: 'Speed Run' },
        { name: '💎𝙱𝚕𝚘𝚡 𝙵𝚛𝚞𝚒𝚝𝚜 𝙺𝚒𝚗𝚐💎', style: 'Blox Fruits King' },
    ],

    discord: [
        { name: '🎧𝓢𝓮𝓻𝓿𝓮𝓻 𝓚𝓲𝓷𝓰🎧', style: 'Server King' },
        { name: '🤖𝕄𝕠𝕕 𝔹𝕠𝕥🤖', style: 'Mod Bot' },
        { name: '💬𝙲𝚑𝚊𝚝 𝙶𝚘𝚍💬', style: 'Chat God' },
        { name: '🎮𝕲𝖆𝖒𝖊𝖗 𝕷𝖔𝖗𝖉🎮', style: 'Gamer Lord' },
        { name: '👾𝓝𝓲𝓽𝓻𝓸 𝓑𝓸𝓸𝓼𝓽𝓮𝓻👾', style: 'Nitro Booster' },
        { name: '🔊𝕍𝕠𝕚𝕔𝕖 ℂ𝕙𝕒𝕥 𝕂𝕚𝕟𝕘🔊', style: 'Voice Chat King' },
        { name: '⚡𝙰𝚍𝚖𝚒𝚗 𝙶𝚘𝚍⚡', style: 'Admin God' },
        { name: '🌐𝕊𝕖𝕣𝕧𝕖𝕣 𝔹𝕠𝕤𝕤🌐', style: 'Server Boss' },
        { name: '🎙️𝓢𝓽𝓻𝓮𝓪𝓶𝓮𝓻🎙️', style: 'Streamer' },
        { name: '🏴𝕻𝖎𝖗𝖆𝖙𝖊 𝕶𝖎𝖓𝖌🏴', style: 'Pirate King' },
    ],

    cute: [
        { name: '꧁♡𝓒𝓾𝓭𝓭𝓵𝓮 𝓑𝓾𝓷𝓷𝔂♡꧂', style: 'Cuddle Bunny' },
        { name: '✿𝕊𝕨𝕖𝕖𝕥 𝕊𝕦𝕘𝕒𝕣✿', style: 'Sweet Sugar' },
        { name: '🍓𝙱𝚎𝚛𝚛𝚢 𝙱𝚊𝚋𝚎🍓', style: 'Berry Babe' },
        { name: '♡𝓗𝓸𝓷𝓮𝔂 𝓑𝓮𝓪𝓻♡', style: 'Honey Bear' },
        { name: '🌸𝕃𝕚𝕥𝕥𝕝𝕖 𝔻𝕒𝕚𝕤𝕪🌸', style: 'Little Daisy' },
        { name: '꧁✿𝓒𝓱𝓮𝓻𝓻𝔂 𝓑𝓵𝓸𝓼𝓼𝓸𝓶✿꧂', style: 'Cherry Blossom' },
        { name: '🐰𝙱𝚞𝚗𝚗𝚢 𝙱𝚘𝚘🐰', style: 'Bunny Boo' },
        { name: '♡𝕄𝕒𝕣𝕤𝕙𝕞𝕒𝕝𝕝𝕠𝕨♡', style: 'Marshmallow' },
        { name: '🧁𝓒𝓾𝓹𝓬𝓪𝓴𝓮 𝓟𝓲𝔁𝓲𝓮🧁', style: 'Cupcake Pixie' },
        { name: '✦𝙿𝚎𝚊𝚌𝚑𝚢 𝙺𝚎𝚎𝚗✦', style: 'Peachy Keen' },
        { name: '🌷𝕊𝕠𝕗𝕥 𝔹𝕦𝕟🌷', style: 'Soft Bun' },
        { name: '꧁♡𝓜𝓲𝓷𝓲 𝓜𝓸𝓬𝓱𝓲♡꧂', style: 'Mini Mochi' },
    ],

    cool: [
        { name: '꧁☬𝓒𝓸𝓸𝓵 𝓓𝓾𝓭𝓮☬꧂', style: 'Cool Dude' },
        { name: '✦𝕀𝕔𝕖 𝕄𝕒𝕟✦', style: 'Ice Man' },
        { name: '😎𝙲𝚑𝚒𝚕𝚕 𝚅𝚒𝚋𝚎𝚜😎', style: 'Chill Vibes' },
        { name: '⚡𝓕𝓻𝓸𝓼𝓽 𝓚𝓲𝓷𝓰⚡', style: 'Frost King' },
        { name: '★彡𝕊𝕨𝕒𝕘 𝕄𝕒𝕤𝕥𝕖𝕣彡★', style: 'Swag Master' },
        { name: '꧁❄️𝕮𝖔𝖑𝖉 𝕭𝖑𝖔𝖔𝖉❄️꧂', style: 'Cold Blood' },
        { name: '🔥𝙷𝚘𝚝 𝚂𝚑𝚘𝚝🔥', style: 'Hot Shot' },
        { name: '✰𝓢𝓶𝓸𝓸𝓽𝓱 𝓒𝓻𝓲𝓶𝓲𝓷𝓪𝓵✰', style: 'Smooth Criminal' },
        { name: '⚡𝕊𝕥𝕖𝕖𝕝 𝕍𝕚𝕡𝕖𝕣⚡', style: 'Steel Viper' },
        { name: '꧁☆𝙼𝚛 𝙲𝚘𝚘𝚕☆꧂', style: 'Mr Cool' },
        { name: '🌀𝓒𝔂𝓬𝓵𝓸𝓷𝓮🌀', style: 'Cyclone' },
        { name: '✦𝕄𝕒𝕧𝕖𝕣𝕚𝕔𝕜✦', style: 'Maverick' },
    ],

    fancy: [
        { name: '꧁✨𝓕𝓪𝓷𝓬𝔂 𝓢𝓸𝓾𝓵✨꧂', style: 'Fancy Soul' },
        { name: '💎𝔻𝕚𝕒𝕞𝕠𝕟𝕕 𝔻𝕦𝕤𝕥💎', style: 'Diamond Dust' },
        { name: '✦𝓖𝓸𝓵𝓭𝓮𝓷 𝓖𝓻𝓪𝓬𝓮✦', style: 'Golden Grace' },
        { name: '👑𝙴𝚕𝚒𝚝𝚎 𝚂𝚝𝚢𝚕𝚎👑', style: 'Elite Style' },
        { name: '꧁💫𝕽𝖔𝖞𝖆𝖑 𝕲𝖑𝖆𝖒💫꧂', style: 'Royal Glam' },
        { name: '✨𝒱𝑒𝓁𝓋𝑒𝓉 𝒟𝓇𝑒𝒶𝓂✨', style: 'Velvet Dream' },
        { name: '🌟𝕊𝕚𝕝𝕜 𝕊𝕡𝕝𝕖𝕟𝕕𝕠𝕣🌟', style: 'Silk Splendor' },
        { name: '꧁♛𝓟𝓵𝓪𝓽𝓲𝓷𝓾𝓶 𝓟𝓻𝓲𝓷𝓬𝓮♛꧂', style: 'Platinum Prince' },
        { name: '💖𝙿𝚎𝚊𝚛𝚕 𝙶𝚕𝚘𝚠💖', style: 'Pearl Glow' },
        { name: '✦𝕮𝖗𝖞𝖘𝖙𝖆𝖑 𝕮𝖍𝖆𝖗𝖒✦', style: 'Crystal Charm' },
        { name: '🌹𝓛𝓾𝔁𝓮 𝓛𝓲𝓯𝓮🌹', style: 'Luxe Life' },
        { name: '꧁✨𝕆𝕡𝕒𝕝 𝕊𝕥𝕒𝕣✨꧂', style: 'Opal Star' },
    ],

    love: [
        { name: '꧁❤️𝓕𝓸𝓻𝓮𝓿𝓮𝓻 𝓛𝓸𝓿𝓮❤️꧂', style: 'Forever Love' },
        { name: '💕𝕄𝕪 𝕙𝕖𝕒𝕣𝕥💕', style: 'My Heart' },
        { name: '♡𝓛𝓸𝓿𝓮 𝓑𝓲𝓻𝓭♡', style: 'Love Bird' },
        { name: '💖𝙷𝚎𝚊𝚛𝚝 𝚂𝚝𝚎𝚊𝚕𝚎𝚛💖', style: 'Heart Stealer' },
        { name: '꧁💞𝕊𝕨𝕖𝕖𝕥 𝕃𝕠𝕧𝕖💞꧂', style: 'Sweet Love' },
        { name: '❤️‍🔥𝓦𝓲𝓵𝓭 𝓗𝓮𝓪𝓻𝓽❤️‍🔥', style: 'Wild Heart' },
        { name: '💘𝙲𝚞𝚙𝚒𝚍 𝙺𝚒𝚜𝚜💘', style: 'Cupid Kiss' },
        { name: '♡𝕃𝕠𝕧𝕖 𝕊𝕥𝕣𝕦𝕔𝕜♡', style: 'Love Struck' },
        { name: '💝𝓜𝓲𝓼𝓼 𝓢𝓦𝓮𝓮𝓽𝓱𝓮𝓪𝓻𝓽💝', style: 'Miss Sweetheart' },
        { name: '꧁❤️𝕷𝖔𝖛𝖊 𝕻𝖔𝖙𝖎𝖔𝖓❤️꧂', style: 'Love Potion' },
        { name: '💕𝙴𝚝𝚎𝚛𝚗𝚊𝚕 𝙵𝚕𝚊𝚖𝚎💕', style: 'Eternal Flame' },
        { name: '♡𝓗𝓮𝓪𝓻𝓽 & 𝓢𝓸𝓾𝓵♡', style: 'Heart And Soul' },
    ],

    crazy: [
        { name: '꧁🤪𝓒𝓻𝓪𝔃𝔂 𝓜𝓲𝓷𝓭🤪꧂', style: 'Crazy Mind' },
        { name: '⚡𝕎𝕚𝕝𝕕 𝕆𝕟𝕖⚡', style: 'Wild One' },
        { name: '🌀𝙼𝚊𝚍 𝙶𝚎𝚗𝚒𝚞𝚜🌀', style: 'Mad Genius' },
        { name: '★彡𝓒𝓱𝓪𝓸𝓼 𝓚𝓲𝓷𝓰彡★', style: 'Chaos King' },
        { name: '꧁😜𝕄𝕒𝕕 𝕄𝕒𝕩😜꧂', style: 'Mad Max' },
        { name: '🔥𝓛𝓸𝓸𝓼𝓮 𝓒𝓪𝓷𝓷𝓸𝓷🔥', style: 'Loose Cannon' },
        { name: '⚡𝙿𝚜𝚢𝚌𝚑𝚘 𝚅𝚒𝚋𝚎⚡', style: 'Psycho Vibe' },
        { name: '꧁🌪️𝕎𝕚𝕝𝕕 𝕊𝕥𝕠𝕣𝕞🌪️꧂', style: 'Wild Storm' },
        { name: '😈𝓒𝓻𝓪𝔃𝔂 𝓓𝓮𝓿𝓲𝓵😈', style: 'Crazy Devil' },
        { name: '✦𝙻𝚘𝚌𝚘 𝙻𝚎𝚐𝚎𝚗𝚍✦', style: 'Loco Legend' },
        { name: '🎢𝕀𝕟𝕤𝕒𝕟𝕖 𝕄𝕠𝕕𝕖🎢', style: 'Insane Mode' },
        { name: '꧁🤡𝓙𝓸𝓴𝓮𝓻 𝓦𝓲𝓵𝓭🤡꧂', style: 'Joker Wild' },
    ],

    sword: [
        { name: '꧁⚔️𝓑𝓵𝓪𝓭𝓮 𝓜𝓪𝓼𝓽𝓮𝓻⚔️꧂', style: 'Blade Master' },
        { name: '⚔️𝕊𝕨𝕠𝕣𝕕 𝕂𝕚𝕟𝕘⚔️', style: 'Sword King' },
        { name: '🗡️𝙎𝙩𝙚𝙚𝙡 𝙀𝙙𝙜𝙚🗡️', style: 'Steel Edge' },
        { name: '☬𝓢𝓱𝓪𝓭𝓸𝔀 𝓑𝓵𝓪𝓭𝓮☬', style: 'Shadow Blade' },
        { name: '꧁⚔️𝕯𝖆𝖗𝖐 𝕾𝖑𝖆𝖞𝖊𝖗⚔️꧂', style: 'Dark Slayer' },
        { name: '🗡️𝕂𝕒𝕥𝕒𝕟𝕒 𝕃𝕠𝕣𝕕🗡️', style: 'Katana Lord' },
        { name: '⚔️𝙱𝚕𝚊𝚍𝚎 𝙳𝚊𝚗𝚌𝚎𝚛⚔️', style: 'Blade Dancer' },
        { name: '꧁☠️𝓡𝓮𝓪𝓹𝓮𝓻 𝓑𝓵𝓪𝓭𝓮☠️꧂', style: 'Reaper Blade' },
        { name: '🗡️𝕊𝕒𝕞𝕦𝕣𝕒𝕚 𝕊𝕠𝕦𝕝🗡️', style: 'Samurai Soul' },
        { name: '⚔️𝙎𝙬𝙤𝙧𝙙 𝙎𝙖𝙞𝙣𝙩⚔️', style: 'Sword Saint' },
        { name: '꧁⚔️𝓘𝓻𝓸𝓷 𝓕𝓪𝓷𝓰⚔️꧂', style: 'Iron Fang' },
        { name: '🗡️𝕍𝕠𝕣𝕡𝕒𝕝 𝔼𝕕𝕘𝕖🗡️', style: 'Vorpal Edge' },
    ],

    star: [
        { name: '꧁✦𝓢𝓱𝓲𝓷𝓲𝓷𝓰 𝓢𝓽𝓪𝓻✦꧂', style: 'Shining Star' },
        { name: '✰𝕊𝕥𝕒𝕣 𝕃𝕚𝕘𝕙𝕥✰', style: 'Star Light' },
        { name: '🌟𝙎𝙩𝙖𝙧 𝘿𝙪𝙨𝙩🌟', style: 'Star Dust' },
        { name: '✦𝓒𝓸𝓼𝓶𝓲𝓬 𝓢𝓽𝓪𝓻✦', style: 'Cosmic Star' },
        { name: '꧁✰𝕊𝕦𝕡𝕖𝕣 𝕊𝕥𝕒𝕣✰꧂', style: 'Super Star' },
        { name: '🌠𝓢𝓱𝓸𝓸𝓽𝓲𝓷𝓰 𝓢𝓽𝓪𝓻🌠', style: 'Shooting Star' },
        { name: '✦𝙽𝚘𝚛𝚝𝚑 𝚂𝚝𝚊𝚛✦', style: 'North Star' },
        { name: '꧁✰𝕊𝕥𝕒𝕣 𝕊𝕡𝕒𝕣𝕜𝕝𝕖✰꧂', style: 'Star Sparkle' },
        { name: '💫𝓖𝓪𝓵𝓪𝔁𝔂 𝓢𝓽𝓪𝓻💫', style: 'Galaxy Star' },
        { name: '✦𝕊𝕥𝕖𝕝𝕝𝕒𝕣✦', style: 'Stellar' },
        { name: '🌟𝙱𝚛𝚒𝚐𝚑𝚝 𝚂𝚝𝚊𝚛🌟', style: 'Bright Star' },
        { name: '꧁✰𝓢𝓽𝓪𝓻 𝓠𝓾𝓮𝓮𝓷✰꧂', style: 'Star Queen' },
    ],

    serious: [
        { name: '꧁☬𝓢𝓮𝓻𝓲𝓸𝓾𝓼 𝓜𝓲𝓷𝓭☬꧂', style: 'Serious Mind' },
        { name: '⚡𝕊𝕥𝕠𝕟𝕖 𝔽𝕒𝕔𝕖⚡', style: 'Stone Face' },
        { name: '✦𝙲𝚊𝚕𝚖 𝙿𝚛𝚘✦', style: 'Calm Pro' },
        { name: '★𝓢𝓲𝓵𝓮𝓷𝓽 𝓘𝓬𝓮★', style: 'Silent Ice' },
        { name: '꧁☬𝕄𝕣 𝕊𝕥𝕖𝕒𝕕𝕪☬꧂', style: 'Mr Steady' },
        { name: '⚙️𝓕𝓸𝓬𝓾𝓼𝓮𝓭 𝓜𝓲𝓷𝓭⚙️', style: 'Focused Mind' },
        { name: '✦𝕊𝕥𝕖𝕖𝕝 𝕄𝕒𝕟𝕟𝕖𝕣✦', style: 'Steel Manner' },
        { name: '꧁♛𝙶𝚛𝚊𝚟𝚎 𝙻𝚘𝚛𝚍♛꧂', style: 'Grave Lord' },
        { name: '⚡𝓒𝓸𝓵𝓭 𝓛𝓸𝓰𝓲𝓬⚡', style: 'Cold Logic' },
        { name: '✦𝕊𝕥𝕠𝕚𝕔 𝕊𝕠𝕦𝕝✦', style: 'Stoic Soul' },
        { name: '★𝙿𝚘𝚔𝚎𝚛 𝙵𝚊𝚌𝚎★', style: 'Poker Face' },
        { name: '꧁☬𝓘𝓻𝓸𝓷 𝓦𝓲𝓵𝓵☬꧂', style: 'Iron Will' },
    ],

    angry: [
        { name: '꧁🔥𝓡𝓪𝓰𝓮 𝓜𝓸𝓭𝓮🔥꧂', style: 'Rage Mode' },
        { name: '⚡𝕗𝕦𝕣𝕪 𝕂𝕚𝕟𝕘⚡', style: 'Fury King' },
        { name: '😡𝙰𝚗𝚐𝚎𝚛 𝙱𝚎𝚊𝚜𝚝😡', style: 'Anger Beast' },
        { name: '🔥𝓦𝓻𝓪𝓽𝓱 𝓛𝓸𝓻𝓭🔥', style: 'Wrath Lord' },
        { name: '꧁☠️𝕽𝖆𝖌𝖎𝖓𝖌 𝕱𝖎𝖗𝖊☠️꧂', style: 'Raging Fire' },
        { name: '💢𝕊𝕥𝕠𝕣𝕞 𝔽𝕦𝕣𝕪💢', style: 'Storm Fury' },
        { name: '🔥𝙷𝚘𝚝 𝚃𝚎𝚖𝚙𝚎𝚛🔥', style: 'Hot Temper' },
        { name: '꧁😤𝓕𝓲𝓮𝓻𝓬𝓮 𝓢𝓸𝓾𝓵😤꧂', style: 'Fierce Soul' },
        { name: '⚡𝕄𝕒𝕕 𝔽𝕦𝕣𝕪⚡', style: 'Mad Fury' },
        { name: '🌋𝓥𝓸𝓵𝓬𝓪𝓷𝓸 𝓡𝓪𝓰𝓮🌋', style: 'Volcano Rage' },
        { name: '꧁🔥𝙱𝚞𝚛𝚗𝚒𝚗𝚐 𝙰𝚗𝚐𝚎𝚛🔥꧂', style: 'Burning Anger' },
        { name: '💥𝕊𝕒𝕧𝕒𝕘𝕖 𝕊𝕥𝕠𝕣𝕞💥', style: 'Savage Storm' },
    ],

    sad: [
        { name: '꧁💧𝓛𝓸𝓷𝓮𝓵𝔂 𝓢𝓸𝓾𝓵💧꧂', style: 'Lonely Soul' },
        { name: '🥀𝕊𝕒𝕕 𝕊𝕡𝕚𝕣𝕚𝕥🥀', style: 'Sad Spirit' },
        { name: '😢𝙻𝚘𝚜𝚝 𝙷𝚘𝚙𝚎😢', style: 'Lost Hope' },
        { name: '🌧️𝓡𝓪𝓲𝓷𝔂 𝓗𝓮𝓪𝓻𝓽🌧️', style: 'Rainy Heart' },
        { name: '꧁💔𝕊𝕚𝕝𝕖𝕟𝕥 𝕋𝕖𝕒𝕣𝕤💔꧂', style: 'Silent Tears' },
        { name: '🥀𝓕𝓪𝓭𝓮𝓭 𝓢𝓸𝓾𝓵🥀', style: 'Faded Soul' },
        { name: '🌑𝙴𝚖𝚙𝚝𝚢 𝙷𝚎𝚊𝚛𝚝🌑', style: 'Empty Heart' },
        { name: '꧁💧𝕃𝕠𝕤𝕥 𝕊𝕠𝕦𝕝💧꧂', style: 'Lost Soul' },
        { name: '😞𝓑𝓵𝓾𝓮 𝓜𝓸𝓸𝓭😞', style: 'Blue Mood' },
        { name: '🥀𝕎𝕚𝕝𝕥𝕖𝕕 𝕃𝕠𝕧𝕖🥀', style: 'Wilted Love' },
        { name: '🌧️𝙶𝚛𝚎𝚢 𝚂𝚔𝚒𝚎𝚜🌧️', style: 'Grey Skies' },
        { name: '꧁💧𝓣𝓮𝓪𝓻 𝓓𝓻𝓸𝓹💧꧂', style: 'Tear Drop' },
    ],

    attitude: [
        { name: '꧁☬𝓢𝓲𝓵𝓮𝓷𝓽 𝓚𝓲𝓵𝓵𝓮𝓻☬꧂', style: 'Silent Killer' },
        { name: '😏𝔸𝕥𝕥𝕚𝕥𝕦𝕕𝕖 𝕂𝕚𝕟𝕘😏', style: 'Attitude King' },
        { name: '⚡𝙱𝚘𝚜𝚜 𝙼𝚘𝚍𝚎⚡', style: 'Boss Mode' },
        { name: '★彡𝓢𝔀𝓪𝓰 𝓚𝓲𝓷𝓰彡★', style: 'Swag King' },
        { name: '꧁😎𝕊𝕒𝕧𝕒𝕘𝕖 𝕊𝕠𝕦𝕝😎꧂', style: 'Savage Soul' },
        { name: '🔥𝓝𝓸 𝓡𝓾𝓵𝓮𝓼🔥', style: 'No Rules' },
        { name: '⚡𝙺𝚒𝚗𝚐 𝙾𝚏 𝙰𝚝𝚝𝚒𝚝𝚞𝚍𝚎⚡', style: 'King Of Attitude' },
        { name: '꧁😈𝕯𝖆𝖓𝖌𝖊𝖗 𝕬𝖑𝖊𝖗𝖙😈꧂', style: 'Danger Alert' },
        { name: '💯𝓢𝓮𝓵𝓯 𝓜𝓪𝓭𝓮💯', style: 'Self Made' },
        { name: '🤘𝕄𝕣 𝔸𝕥𝕥𝕚𝕥𝕦𝕕𝕖🤘', style: 'Mr Attitude' },
        { name: '꧁☬𝙱𝚘𝚕𝚍 𝙱𝚘𝚜𝚜☬꧂', style: 'Bold Boss' },
        { name: '😏𝓡𝓮𝓫𝓮𝓵 𝓢𝓸𝓾𝓵😏', style: 'Rebel Soul' },
    ],

    happy: [
        { name: '꧁😊𝓗𝓪𝓹𝓹𝔂 𝓢𝓸𝓾𝓵😊꧂', style: 'Happy Soul' },
        { name: '☀️𝕊𝕦𝕟𝕟𝕪 𝕍𝕚𝕓𝕖𝕤☀️', style: 'Sunny Vibes' },
        { name: '🌈𝙹𝚘𝚢 𝚁𝚒𝚍𝚎🌈', style: 'Joy Ride' },
        { name: '✨𝓢𝓶𝓲𝓵𝓮 𝓜𝓸𝓻𝓮✨', style: 'Smile More' },
        { name: '꧁😄𝕊𝕞𝕚𝕝𝕖𝕪 𝕂𝕚𝕟𝕘😄꧂', style: 'Smiley King' },
        { name: '🌻𝓖𝓸𝓸𝓭 𝓥𝓲𝓫𝓮𝓼🌻', style: 'Good Vibes' },
        { name: '☀️𝙱𝚛𝚒𝚐𝚑𝚝 𝙳𝚊𝚢☀️', style: 'Bright Day' },
        { name: '꧁🎉𝕁𝕠𝕪𝕗𝕦𝕝 𝕊𝕠𝕦𝕝🎉꧂', style: 'Joyful Soul' },
        { name: '🌈𝓟𝓾𝓻𝓮 𝓙𝓸𝔂🌈', style: 'Pure Joy' },
        { name: '😁𝕊𝕦𝕟𝕤𝕙𝕚𝕟𝕖 𝕂𝕚𝕕😁', style: 'Sunshine Kid' },
        { name: '✨𝙷𝚊𝚙𝚙𝚢 𝙶𝚘 𝙻𝚞𝚌𝚔𝚢✨', style: 'Happy Go Lucky' },
        { name: '꧁🌟𝓒𝓱𝓮𝓮𝓻 𝓤𝓹🌟꧂', style: 'Cheer Up' },
    ],

    'broken-heart': [
        { name: '꧁💔𝓑𝓻𝓸𝓴𝓮𝓷 𝓢𝓸𝓾𝓵💔꧂', style: 'Broken Soul' },
        { name: '💔𝕃𝕠𝕟𝕖𝕝𝕪 𝕙𝕖𝕒𝕣𝕥💔', style: 'Lonely Heart' },
        { name: '🥀𝙎𝙝𝙖𝙩𝙩𝙚𝙧𝙚𝙙 𝙇𝙤𝙫𝙚🥀', style: 'Shattered Love' },
        { name: '💔𝓒𝓻𝓪𝓬𝓴𝓮𝓭 𝓗𝓮𝓪𝓻𝓽💔', style: 'Cracked Heart' },
        { name: '꧁🥀𝕯𝖊𝖆𝖉 𝕷𝖔𝖛𝖊🥀꧂', style: 'Dead Love' },
        { name: '💔𝙱𝚛𝚘𝚔𝚎𝚗 𝙿𝚒𝚎𝚌𝚎𝚜💔', style: 'Broken Pieces' },
        { name: '🖤𝓔𝓶𝓹𝓽𝔂 𝓛𝓸𝓿𝓮🖤', style: 'Empty Love' },
        { name: '꧁💔𝕋𝕠𝕣𝕟 𝔸𝕡𝕒𝕣𝕥💔꧂', style: 'Torn Apart' },
        { name: '🥀𝙻𝚘𝚜𝚝 𝙻𝚘𝚟𝚎𝚛🥀', style: 'Lost Lover' },
        { name: '💔𝓕𝓪𝓭𝓮𝓭 𝓗𝓮𝓪𝓻𝓽💔', style: 'Faded Heart' },
        { name: '꧁🖤𝕊𝕔𝕒𝕣𝕣𝕖𝕕 𝕊𝕠𝕦𝕝🖤꧂', style: 'Scarred Soul' },
        { name: '💔𝙷𝚎𝚊𝚛𝚝𝚕𝚎𝚜𝚜💔', style: 'Heartless' },
    ],

    sexy: [
        { name: '꧁🔥𝓗𝓸𝓽 𝓢𝓽𝓾𝓯𝓯🔥꧂', style: 'Hot Stuff' },
        { name: '💋𝕊𝕦𝕝𝕥𝕣𝕪 𝕊𝕠𝕦𝕝💋', style: 'Sultry Soul' },
        { name: '🔥𝙵𝚒𝚛𝚎 𝙺𝚒𝚜𝚜🔥', style: 'Fire Kiss' },
        { name: '💄𝓖𝓵𝓪𝓶 𝓠𝓾𝓮𝓮𝓷💄', style: 'Glam Queen' },
        { name: '꧁💋𝕊𝕖𝕕𝕦𝕔𝕥𝕚𝕧𝕖💋꧂', style: 'Seductive' },
        { name: '🌶️𝓢𝓹𝓲𝓬𝔂 𝓑𝓪𝓫𝓮🌶️', style: 'Spicy Babe' },
        { name: '💕𝙵𝚕𝚒𝚛𝚝 𝚀𝚞𝚎𝚎𝚗💕', style: 'Flirt Queen' },
        { name: '꧁🔥𝕍𝕖𝕝𝕧𝕖𝕥 𝕂𝕚𝕤𝕤🔥꧂', style: 'Velvet Kiss' },
        { name: '💋𝓓𝓲𝓿𝓪 𝓥𝓲𝓫𝓮𝓼💋', style: 'Diva Vibes' },
        { name: '🌹𝕄𝕚𝕕𝕟𝕚𝕘𝕙𝕥 ℂ𝕙𝕒𝕣𝕞🌹', style: 'Midnight Charm' },
        { name: '꧁💄𝙱𝚘𝚖𝚋𝚜𝚑𝚎𝚕𝚕💄꧂', style: 'Bombshell' },
        { name: '🔥𝓡𝓮𝓭 𝓗𝓸𝓽🔥', style: 'Red Hot' },
    ],

    devil: [
        { name: '꧁☬𝓓𝓪𝓻𝓴 𝓓𝓮𝓶𝓸𝓷☬꧂', style: 'Dark Demon' },
        { name: '⛧𝕳𝖊𝖑𝖑 𝕷𝖔𝖗𝖉⛧', style: 'Hell Lord' },
        { name: '😈𝘿𝙚𝙫𝙞𝙡 𝙎𝙤𝙪𝙡😈', style: 'Devil Soul' },
        { name: '☠️𝓢𝓪𝓽𝓪𝓷 𝓚𝓲𝓷𝓰☠️', style: 'Satan King' },
        { name: '꧁⛧𝕯𝖊𝖒𝖔𝖓 𝕷𝖔𝖗𝖉⛧꧂', style: 'Demon Lord' },
        { name: '🔥𝙷𝚎𝚕𝚕 𝙵𝚒𝚛𝚎🔥', style: 'Hell Fire' },
        { name: '☬𝓓𝓪𝓻𝓴 𝓢𝓸𝓾𝓵☬', style: 'Dark Soul' },
        { name: '꧁😈𝕊𝕚𝕟 𝕃𝕠𝕣𝕕😈꧂', style: 'Sin Lord' },
        { name: '⛧𝓘𝓷𝓯𝓮𝓻𝓷𝓸 𝓚𝓲𝓷𝓰⛧', style: 'Inferno King' },
        { name: '☠️𝕊𝕠𝕦𝕝 𝔼𝕒𝕥𝕖𝕣☠️', style: 'Soul Eater' },
        { name: '꧁☬𝙳𝚊𝚛𝚔 𝙻𝚘𝚛𝚍☬꧂', style: 'Dark Lord' },
        { name: '😈𝓦𝓲𝓬𝓴𝓮𝓭 𝓢𝓸𝓾𝓵😈', style: 'Wicked Soul' },
    ],

    confused: [
        { name: '꧁🤔𝓒𝓸𝓷𝓯𝓾𝓼𝓮𝓭 𝓢𝓸𝓾𝓵🤔꧂', style: 'Confused Soul' },
        { name: '❓𝕃𝕠𝕤𝕥 𝕄𝕚𝕟𝕕❓', style: 'Lost Mind' },
        { name: '🤷𝙽𝚘 𝙲𝚕𝚞𝚎🤷', style: 'No Clue' },
        { name: '🌀𝓜𝓲𝔁𝓮𝓭 𝓤𝓹🌀', style: 'Mixed Up' },
        { name: '꧁❔𝕎𝕙𝕠 𝔸𝕞 𝕀❔꧂', style: 'Who Am I' },
        { name: '🤨𝓦𝓱𝓪𝓽 𝓝𝓸𝔀🤨', style: 'What Now' },
        { name: '❓𝙻𝚘𝚜𝚝 𝙰𝚐𝚊𝚒𝚗❓', style: 'Lost Again' },
        { name: '꧁🤔𝔹𝕝𝕒𝕟𝕜 𝕄𝕚𝕟𝕕🤔꧂', style: 'Blank Mind' },
        { name: '🌫️𝓕𝓸𝓰𝓰𝔂 𝓗𝓮𝓪𝓭🌫️', style: 'Foggy Head' },
        { name: '🤷𝕀𝔻𝕂 𝕍𝕚𝕓𝕖𝕤🤷', style: 'IDK Vibes' },
        { name: '❔𝙿𝚞𝚣𝚣𝚕𝚎𝚍 𝙾𝚗𝚎❔', style: 'Puzzled One' },
        { name: '꧁🤪𝓓𝓲𝔃𝔃𝔂 𝓜𝓲𝓷𝓭🤪꧂', style: 'Dizzy Mind' },
    ],

    dancing: [
        { name: '꧁💃𝓓𝓪𝓷𝓬𝓮 𝓚𝓲𝓷𝓰💃꧂', style: 'Dance King' },
        { name: '🕺𝔻𝕒𝕟𝕔𝕖 𝕄𝕒𝕔𝕙𝕚𝕟𝕖🕺', style: 'Dance Machine' },
        { name: '✨𝙶𝚛𝚘𝚘𝚟𝚎 𝙼𝚊𝚜𝚝𝚎𝚛✨', style: 'Groove Master' },
        { name: '💃𝓡𝓱𝔂𝓽𝓱𝓶 𝓠𝓾𝓮𝓮𝓷💃', style: 'Rhythm Queen' },
        { name: '꧁🎶𝕊𝕥𝕖𝕡 𝕄𝕒𝕤𝕥𝕖𝕣🎶꧂', style: 'Step Master' },
        { name: '🕺𝓕𝓵𝓸𝓸𝓻 𝓚𝓲𝓵𝓵𝓮𝓻🕺', style: 'Floor Killer' },
        { name: '✨𝙼𝚘𝚟𝚎 𝙼𝚊𝚔𝚎𝚛✨', style: 'Move Maker' },
        { name: '꧁💃𝔻𝕚𝕤𝕔𝕠 𝕊𝕥𝕒𝕣💃꧂', style: 'Disco Star' },
        { name: '🎵𝓑𝓮𝓪𝓽 𝓓𝓻𝓸𝓹🎵', style: 'Beat Drop' },
        { name: '🕺𝕊𝕒𝕝𝕤𝕒 𝕊𝕠𝕦𝕝🕺', style: 'Salsa Soul' },
        { name: '✨𝙱𝚘𝚘𝚐𝚒𝚎 𝙺𝚒𝚗𝚐✨', style: 'Boogie King' },
        { name: '꧁💃𝓣𝓪𝓹 𝓢𝓽𝓪𝓻💃꧂', style: 'Tap Star' },
    ],

    depressed: [
        { name: '꧁🌑𝓓𝓮𝓹𝓻𝓮𝓼𝓼𝓮𝓭 𝓢𝓸𝓾𝓵🌑꧂', style: 'Depressed Soul' },
        { name: '🖤𝕍𝕠𝕚𝕕 𝕊𝕠𝕦𝕝🖤', style: 'Void Soul' },
        { name: '🌧️𝙳𝚊𝚛𝚔 𝙳𝚊𝚢𝚜🌧️', style: 'Dark Days' },
        { name: '🥀𝓝𝓾𝓶𝓫 𝓗𝓮𝓪𝓻𝓽🥀', style: 'Numb Heart' },
        { name: '꧁🌑𝕊𝕚𝕝𝕖𝕟𝕥 𝕊𝕔𝕣𝕖𝕒𝕞🌑꧂', style: 'Silent Scream' },
        { name: '🖤𝓗𝓸𝓵𝓵𝓸𝔀 𝓢𝓸𝓾𝓵🖤', style: 'Hollow Soul' },
        { name: '🌫️𝙻𝚘𝚜𝚝 𝙸𝚗𝚜𝚒𝚍𝚎🌫️', style: 'Lost Inside' },
        { name: '꧁🥀𝔽𝕒𝕕𝕚𝕟𝕘 𝕃𝕚𝕘𝕙𝕥🥀꧂', style: 'Fading Light' },
        { name: '🌑𝓓𝓮𝓮𝓹 𝓢𝓱𝓪𝓭𝓸𝔀🌑', style: 'Deep Shadow' },
        { name: '🖤𝔼𝕞𝕡𝕥𝕪 𝕄𝕚𝕟𝕕🖤', style: 'Empty Mind' },
        { name: '🌧️𝙱𝚛𝚘𝚔𝚎𝚗 𝚆𝚒𝚝𝚑𝚒𝚗🌧️', style: 'Broken Within' },
        { name: '꧁🌑𝓛𝓸𝓼𝓽 𝓢𝓸𝓾𝓵🌑꧂', style: 'Lost Soul' },
    ],

    crying: [
        { name: '꧁😭𝓒𝓻𝔂𝓲𝓷𝓰 𝓢𝓸𝓾𝓵😭꧂', style: 'Crying Soul' },
        { name: '💧𝕋𝕖𝕒𝕣 𝔻𝕣𝕠𝕡💧', style: 'Tear Drop' },
        { name: '😢𝚂𝚊𝚍 𝙴𝚢𝚎𝚜😢', style: 'Sad Eyes' },
        { name: '🌧️𝓦𝓮𝓮𝓹𝓲𝓷𝓰 𝓗𝓮𝓪𝓻𝓽🌧️', style: 'Weeping Heart' },
        { name: '꧁💧𝕊𝕒𝕝𝕥𝕪 𝕋𝕖𝕒𝕣𝕤💧꧂', style: 'Salty Tears' },
        { name: '😭𝓣𝓮𝓪𝓻𝓯𝓾𝓵 𝓢𝓸𝓾𝓵😭', style: 'Tearful Soul' },
        { name: '💦𝙲𝚛𝚢 𝙱𝚊𝚋𝚢💦', style: 'Cry Baby' },
        { name: '꧁🌧️𝕊𝕠𝕓𝕓𝕚𝕟𝕘 𝕊𝕠𝕦𝕝🌧️꧂', style: 'Sobbing Soul' },
        { name: '😢𝓦𝓮𝓽 𝓒𝓱𝓮𝓮𝓴𝓼😢', style: 'Wet Cheeks' },
        { name: '💧𝕄𝕚𝕤𝕥𝕪 𝔼𝕪𝕖𝕤💧', style: 'Misty Eyes' },
        { name: '😭𝙴𝚗𝚍𝚕𝚎𝚜𝚜 𝚃𝚎𝚊𝚛𝚜😭', style: 'Endless Tears' },
        { name: '꧁💧𝓢𝓲𝓵𝓮𝓷𝓽 𝓒𝓻𝔂💧꧂', style: 'Silent Cry' },
    ],

    begging: [
        { name: '꧁🙏𝓟𝓵𝓮𝓪𝓼𝓮 𝓢𝓽𝓪𝔂🙏꧂', style: 'Please Stay' },
        { name: '🥺𝔹𝕖𝕘𝕘𝕚𝕟𝕘 𝕊𝕠𝕦𝕝🥺', style: 'Begging Soul' },
        { name: '🙏𝙿𝚕𝚎𝚊𝚜𝚎 𝙵𝚘𝚛𝚐𝚒𝚟𝚎🙏', style: 'Please Forgive' },
        { name: '🥺𝓒𝓸𝓶𝓮 𝓑𝓪𝓬𝓴🥺', style: 'Come Back' },
        { name: '꧁🙏𝕆𝕟𝕖 𝕄𝕠𝕣𝕖 ℂ𝕙𝕒𝕟𝕔𝕖🙏꧂', style: 'One More Chance' },
        { name: '🥺𝓟𝓵𝓮𝓪𝓼𝓮 𝓝𝓸𝓽𝓲𝓬𝓮 𝓜𝓮🥺', style: 'Please Notice Me' },
        { name: '🙏𝙳𝚘𝚗𝚝 𝙻𝚎𝚊𝚟𝚎🙏', style: 'Dont Leave' },
        { name: '꧁🥺𝕄𝕖𝕣𝕔𝕪 𝕄𝕖🥺꧂', style: 'Mercy Me' },
        { name: '🙏𝓗𝓮𝓪𝓻 𝓜𝔂 𝓟𝓵𝓮𝓪🙏', style: 'Hear My Plea' },
        { name: '🥺𝕁𝕦𝕤𝕥 𝕆𝕟𝕖 𝕎𝕚𝕤𝕙🥺', style: 'Just One Wish' },
        { name: '🙏𝙿𝚕𝚎𝚊𝚍𝚒𝚗𝚐 𝙷𝚎𝚊𝚛𝚝🙏', style: 'Pleading Heart' },
        { name: '꧁🥺𝓦𝓪𝓲𝓽 𝓕𝓸𝓻 𝓜𝓮🥺꧂', style: 'Wait For Me' },
    ],

    bear: [
        { name: '꧁🐻𝓒𝓾𝓭𝓭𝓵𝓮 𝓑𝓮𝓪𝓻🐻꧂', style: 'Cuddle Bear' },
        { name: '🧸𝕋𝕖𝕕𝕕𝕪 𝔹𝕖𝕒𝕣🧸', style: 'Teddy Bear' },
        { name: '🐻𝙷𝚘𝚗𝚎𝚢 𝙱𝚎𝚊𝚛🐻', style: 'Honey Bear' },
        { name: '♡𝓕𝓾𝔃𝔃𝔂 𝓑𝓮𝓪𝓻♡', style: 'Fuzzy Bear' },
        { name: '꧁🐻𝕊𝕠𝕗𝕥 𝔹𝕖𝕒𝕣🐻꧂', style: 'Soft Bear' },
        { name: '🍯𝓢𝓦𝓮𝓮𝓽 𝓑𝓮𝓪𝓻🍯', style: 'Sweet Bear' },
        { name: '🐻𝙿𝚘𝚕𝚊𝚛 𝙱𝚎𝚊𝚛🐻', style: 'Polar Bear' },
        { name: '꧁🧸𝕊𝕟𝕦𝕘𝕘𝕝𝕖 𝔹𝕖𝕒𝕣🧸꧂', style: 'Snuggle Bear' },
        { name: '🐾𝓖𝓻𝓲𝔃𝔃𝓵𝔂 𝓚𝓲𝓷𝓰🐾', style: 'Grizzly King' },
        { name: '🐻𝔹𝕚𝕘 𝔹𝕖𝕒𝕣🐻', style: 'Big Bear' },
        { name: '♡𝙱𝚞𝚋𝚋𝚕𝚎 𝙱𝚎𝚊𝚛♡', style: 'Bubble Bear' },
        { name: '꧁🐻𝓟𝓪𝓷𝓭𝓪 𝓟𝓪𝓵🐻꧂', style: 'Panda Pal' },
    ],

    dog: [
        { name: '꧁🐶𝓟𝓾𝓹𝓹𝔂 𝓛𝓸𝓿𝓮🐶꧂', style: 'Puppy Love' },
        { name: '🐕𝔻𝕠𝕘𝕘𝕠 𝕂𝕚𝕟𝕘🐕', style: 'Doggo King' },
        { name: '🐾𝙿𝚊𝚠 𝙿𝚛𝚒𝚗𝚌𝚎🐾', style: 'Paw Prince' },
        { name: '♡𝓖𝓸𝓸𝓭 𝓑𝓸𝔂♡', style: 'Good Boy' },
        { name: '꧁🐶𝕃𝕠𝕪𝕒𝕝 𝕡𝕒𝕝🐶꧂', style: 'Loyal Pal' },
        { name: '🦴𝓑𝓸𝓷𝓮 𝓗𝓾𝓷𝓽𝓮𝓻🦴', style: 'Bone Hunter' },
        { name: '🐕𝙵𝚞𝚛𝚛𝚢 𝙵𝚛𝚒𝚎𝚗𝚍🐕', style: 'Furry Friend' },
        { name: '꧁🐾𝕊𝕡𝕠𝕥𝕥𝕪🐾꧂', style: 'Spotty' },
        { name: '🐶𝓟𝓾𝓹 𝓢𝓽𝓪𝓻🐶', style: 'Pup Star' },
        { name: '🐕𝔹𝕒𝕣𝕜 𝔹𝕠𝕤𝕤🐕', style: 'Bark Boss' },
        { name: '♡𝙲𝚞𝚝𝚎 𝙿𝚞𝚙♡', style: 'Cute Pup' },
        { name: '꧁🐾𝓦𝓸𝓸𝓯 𝓦𝓪𝓻𝓻𝓲𝓸𝓻🐾꧂', style: 'Woof Warrior' },
    ],

    facebook: [
        { name: '꧁📘𝓕𝓫 𝓢𝓽𝓪𝓻📘꧂', style: 'FB Star' },
        { name: '👍𝕃𝕚𝕜𝕖 𝕂𝕚𝕟𝕘👍', style: 'Like King' },
        { name: '✨𝙿𝚛𝚘𝚏𝚒𝚕𝚎 𝙺𝚒𝚗𝚐✨', style: 'Profile King' },
        { name: '💬𝓢𝓽𝓪𝓽𝓾𝓼 𝓚𝓲𝓷𝓰💬', style: 'Status King' },
        { name: '꧁📘𝕊𝕠𝕔𝕚𝕒𝕝 𝕊𝕥𝕒𝕣📘꧂', style: 'Social Star' },
        { name: '🌐𝓣𝓲𝓶𝓮𝓵𝓲𝓷𝓮 𝓚𝓲𝓷𝓰🌐', style: 'Timeline King' },
        { name: '👑𝙿𝚛𝚘𝚏𝚒𝚕𝚎 𝙱𝚘𝚜𝚜👑', style: 'Profile Boss' },
        { name: '꧁💙𝔽𝕓 𝕂𝕚𝕟𝕘💙꧂', style: 'FB King' },
        { name: '📸𝓢𝓱𝓪𝓻𝓮 𝓢𝓽𝓪𝓻📸', style: 'Share Star' },
        { name: '✦𝕋𝕒𝕘 𝕄𝕒𝕤𝕥𝕖𝕣✦', style: 'Tag Master' },
        { name: '💬𝙲𝚘𝚖𝚖𝚎𝚗𝚝 𝙺𝚒𝚗𝚐💬', style: 'Comment King' },
        { name: '꧁📘𝓦𝓪𝓵𝓵 𝓚𝓲𝓷𝓰📘꧂', style: 'Wall King' },
    ],

    youtube: [
        { name: '꧁▶️𝓒𝓸𝓷𝓽𝓮𝓷𝓽 𝓚𝓲𝓷𝓰▶️꧂', style: 'Content King' },
        { name: '🎬𝕍𝕚𝕕𝕖𝕠 𝕊𝕥𝕒𝕣🎬', style: 'Video Star' },
        { name: '🔔𝚂𝚞𝚋 𝙼𝚊𝚜𝚝𝚎𝚛🔔', style: 'Sub Master' },
        { name: '📹𝓥𝓵𝓸𝓰 𝓚𝓲𝓷𝓰📹', style: 'Vlog King' },
        { name: '꧁▶️𝕋𝕦𝕓𝕖 𝕊𝕥𝕒𝕣▶️꧂', style: 'Tube Star' },
        { name: '🎥𝓒𝓻𝓮𝓪𝓽𝓸𝓻 𝓚𝓲𝓷𝓰🎥', style: 'Creator King' },
        { name: '⭐𝚅𝚒𝚛𝚊𝚕 𝚃𝚞𝚋𝚎⭐', style: 'Viral Tube' },
        { name: '꧁🔴𝕃𝕚𝕧𝕖 𝕊𝕥𝕒𝕣🔴꧂', style: 'Live Star' },
        { name: '🎮𝓖𝓪𝓶𝓲𝓷𝓰 𝓣𝓾𝓫𝓮🎮', style: 'Gaming Tube' },
        { name: '📺𝕊𝕔𝕣𝕖𝕖𝕟 𝕂𝕚𝕟𝕘📺', style: 'Screen King' },
        { name: '🔔𝙻𝚒𝚔𝚎 𝙰𝚗𝚍 𝚂𝚞𝚋🔔', style: 'Like And Sub' },
        { name: '꧁▶️𝓣𝓻𝓮𝓷𝓭𝓲𝓷𝓰 𝓢𝓽𝓪𝓻▶️꧂', style: 'Trending Star' },
    ],

    spotify: [
        { name: '꧁🎵𝓜𝓾𝓼𝓲𝓬 𝓛𝓸𝓿𝓮𝓻🎵꧂', style: 'Music Lover' },
        { name: '🎧𝔹𝕖𝕒𝕥 𝕂𝕚𝕟𝕘🎧', style: 'Beat King' },
        { name: '🎶𝚂𝚘𝚞𝚗𝚍 𝚆𝚊𝚟𝚎🎶', style: 'Sound Wave' },
        { name: '🎵𝓟𝓵𝓪𝔂𝓵𝓲𝓼𝓽 𝓟𝓻𝓸🎵', style: 'Playlist Pro' },
        { name: '꧁🎧𝕋𝕦𝕟𝕖 𝕊𝕥𝕒𝕣🎧꧂', style: 'Tune Star' },
        { name: '🎶𝓜𝓮𝓵𝓸𝓭𝔂 𝓜𝓪𝓴𝓮𝓻🎶', style: 'Melody Maker' },
        { name: '🔊𝙱𝚊𝚜𝚜 𝙱𝚘𝚘𝚜𝚝🔊', style: 'Bass Boost' },
        { name: '꧁🎵𝕍𝕚𝕓𝕖 𝕄𝕒𝕤𝕥𝕖𝕣🎵꧂', style: 'Vibe Master' },
        { name: '🎤𝓢𝓸𝓷𝓰 𝓢𝓸𝓾𝓵🎤', style: 'Song Soul' },
        { name: '🎧𝕃𝕠𝕗𝕚 𝕂𝕚𝕟𝕘🎧', style: 'Lofi King' },
        { name: '🎶𝙳𝚊𝚒𝚕𝚢 𝙼𝚒𝚡🎶', style: 'Daily Mix' },
        { name: '꧁🎵𝓡𝓱𝔂𝓽𝓱𝓶 𝓡𝓲𝓭𝓮𝓻🎵꧂', style: 'Rhythm Rider' },
    ],

    telegram: [
        { name: '꧁✈️𝓣𝓰 𝓢𝓽𝓪𝓻✈️꧂', style: 'TG Star' },
        { name: '💙𝕋𝕖𝕝𝕖 𝕂𝕚𝕟𝕘💙', style: 'Tele King' },
        { name: '📡𝙲𝚑𝚊𝚗𝚗𝚎𝚕 𝙺𝚒𝚗𝚐📡', style: 'Channel King' },
        { name: '💬𝓒𝓱𝓪𝓽 𝓛𝓸𝓻𝓭💬', style: 'Chat Lord' },
        { name: '꧁✈️𝕊𝕖𝕔𝕣𝕖𝕥 𝕊𝕠𝕦𝕝✈️꧂', style: 'Secret Soul' },
        { name: '🤖𝓑𝓸𝓽 𝓜𝓪𝓼𝓽𝓮𝓻🤖', style: 'Bot Master' },
        { name: '🔒𝙿𝚛𝚒𝚟𝚊𝚝𝚎 𝙺𝚒𝚗𝚐🔒', style: 'Private King' },
        { name: '꧁💙𝔾𝕣𝕠𝕦𝕡 𝕃𝕠𝕣𝕕💙꧂', style: 'Group Lord' },
        { name: '📢𝓑𝓻𝓸𝓪𝓭𝓬𝓪𝓼𝓽 𝓚𝓲𝓷𝓰📢', style: 'Broadcast King' },
        { name: '✈️𝕊𝕥𝕚𝕔𝕜𝕖𝕣 𝕊𝕥𝕒𝕣✈️', style: 'Sticker Star' },
        { name: '👻𝙶𝚑𝚘𝚜𝚝 𝙼𝚘𝚍𝚎👻', style: 'Ghost Mode' },
        { name: '꧁✈️𝓢𝓲𝓵𝓮𝓷𝓽 𝓒𝓱𝓪𝓽✈️꧂', style: 'Silent Chat' },
    ],

    tumblr: [
        { name: '꧁🌙𝓐𝓮𝓼𝓽𝓱𝓮𝓽𝓲𝓬 𝓢𝓸𝓾𝓵🌙꧂', style: 'Aesthetic Soul' },
        { name: '🌸𝕊𝕠𝕗𝕥 𝕍𝕚𝕓𝕖𝕤🌸', style: 'Soft Vibes' },
        { name: '✨𝙼𝚘𝚘𝚍 𝙱𝚘𝚊𝚛𝚍✨', style: 'Mood Board' },
        { name: '🌌𝓓𝓪𝓻𝓴 𝓐𝓬𝓪𝓭𝓮𝓶𝓲𝓪🌌', style: 'Dark Academia' },
        { name: '꧁🌙𝕍𝕚𝕟𝕥𝕒𝕘𝕖 𝕊𝕠𝕦𝕝🌙꧂', style: 'Vintage Soul' },
        { name: '🦋𝓓𝓻𝓮𝓪𝓶𝓮𝓻 𝓥𝓲𝓫𝓮🦋', style: 'Dreamer Vibe' },
        { name: '🌑𝙶𝚛𝚞𝚗𝚐𝚎 𝙺𝚒𝚍🌑', style: 'Grunge Kid' },
        { name: '꧁✨𝕄𝕖𝕝𝕒𝕟𝕔𝕙𝕠𝕝𝕪✨꧂', style: 'Melancholy' },
        { name: '🌹𝓟𝓪𝓼𝓽𝓮𝓵 𝓓𝓻𝓮𝓪𝓶🌹', style: 'Pastel Dream' },
        { name: '🌃𝕄𝕚𝕕𝕟𝕚𝕘𝕙𝕥 𝕄𝕠𝕠𝕕🌃', style: 'Midnight Mood' },
        { name: '✨𝙻𝚘𝚏𝚒 𝙳𝚛𝚎𝚊𝚖𝚜✨', style: 'Lofi Dreams' },
        { name: '꧁🌙𝓒𝓸𝓼𝓶𝓲𝓬 𝓥𝓲𝓫𝓮🌙꧂', style: 'Cosmic Vibe' },
    ],

    snapchat: [
        { name: '꧁👻𝓢𝓷𝓪𝓹 𝓢𝓽𝓪𝓻👻꧂', style: 'Snap Star' },
        { name: '⚡𝕊𝕥𝕣𝕖𝕒𝕜 𝕂𝕚𝕟𝕘⚡', style: 'Streak King' },
        { name: '📸𝚂𝚗𝚊𝚙 𝙺𝚒𝚗𝚐📸', style: 'Snap King' },
        { name: '👻𝓖𝓱𝓸𝓼𝓽 𝓜𝓸𝓭𝓮👻', style: 'Ghost Mode' },
        { name: '꧁⚡𝕊𝕥𝕠𝕣𝕪 𝕊𝕥𝕒𝕣⚡꧂', style: 'Story Star' },
        { name: '🎭𝓕𝓲𝓵𝓽𝓮𝓻 𝓚𝓲𝓷𝓰🎭', style: 'Filter King' },
        { name: '✨𝚂𝚗𝚊𝚙 𝚂𝚘𝚞𝚕✨', style: 'Snap Soul' },
        { name: '꧁👻𝔾𝕙𝕠𝕤𝕥 𝕂𝕚𝕟𝕘👻꧂', style: 'Ghost King' },
        { name: '🔥𝓢𝓽𝓻𝓮𝓪𝓴 𝓜𝓪𝓼𝓽𝓮𝓻🔥', style: 'Streak Master' },
        { name: '📷𝕊𝕟𝕒𝕡 𝕊𝕢𝕦𝕒𝕕📷', style: 'Snap Squad' },
        { name: '👻𝚂𝚎𝚗𝚍 𝚂𝚗𝚊𝚙👻', style: 'Send Snap' },
        { name: '꧁⚡𝓢𝓷𝓪𝓹 𝓛𝓸𝓻𝓭⚡꧂', style: 'Snap Lord' },
    ],

    fortnite: [
        { name: '꧁👑𝓥𝓲𝓬𝓽𝓸𝓻𝔂 𝓡𝓸𝔂𝓪𝓵𝓮👑꧂', style: 'Victory Royale' },
        { name: '⚡𝕊𝕜𝕚𝕟 𝕂𝕚𝕟𝕘⚡', style: 'Skin King' },
        { name: '☬𝓑𝓾𝓲𝓵𝓭 𝓜𝓪𝓼𝓽𝓮𝓻☬', style: 'Build Master' },
        { name: '🔫𝙿𝚞𝚖𝚙 𝙺𝚒𝚗𝚐🔫', style: 'Pump King' },
        { name: '꧁☬𝕊𝕥𝕠𝕣𝕞 ℂ𝕙𝕒𝕤𝕖𝕣☬꧂', style: 'Storm Chaser' },
        { name: '⛏️𝓛𝓸𝓸𝓽 𝓛𝓸𝓻𝓭⛏️', style: 'Loot Lord' },
        { name: '🪂𝙳𝚛𝚘𝚙 𝙺𝚒𝚗𝚐🪂', style: 'Drop King' },
        { name: '꧁⚡𝕊𝕟𝕚𝕡𝕖 𝔾𝕠𝕕⚡꧂', style: 'Snipe God' },
        { name: '☬𝓣𝓲𝓵𝓽𝓮𝓭 𝓣𝓮𝓻𝓻𝓸𝓻☬', style: 'Tilted Terror' },
        { name: '🏆𝔹𝕦𝕤𝕙 𝔹𝕖𝕒𝕤𝕥🏆', style: 'Bush Beast' },
        { name: '꧁⚔️𝙳𝚎𝚏𝚊𝚞𝚕𝚝 𝙺𝚒𝚕𝚕𝚎𝚛⚔️꧂', style: 'Default Killer' },
        { name: '☬𝕊𝕨𝕖𝕒𝕥 𝕃𝕠𝕣𝕕☬', style: 'Sweat Lord' },
    ],

    bgmi: [
        { name: '꧁☬𝓑𝓖𝓜𝓘 𝓚𝓲𝓷𝓰☬꧂', style: 'BGMI King' },
        { name: '⚡𝕊𝕔𝕒𝕣 𝕂𝕚𝕟𝕘⚡', style: 'SCAR King' },
        { name: '☬𝓒𝓸𝓷𝓺𝓾𝓮𝓻𝓸𝓻☬', style: 'Conqueror' },
        { name: '🎯𝙰𝚆𝙼 𝙶𝚘𝚍🎯', style: 'AWM God' },
        { name: '꧁⚔️𝕄𝟜 𝔹𝕖𝕒𝕤𝕥⚔️꧂', style: 'M4 Beast' },
        { name: '╾━╤デ╦︻ 𝓢𝓷𝓲𝓹𝓮𝓻', style: 'BGMI Sniper' },
        { name: '☬ᴴᴱᴬᴰˢᴴᴼᵀ ᴷᴵᴺᴳ☬', style: 'Headshot King' },
        { name: '꧁🏆𝕋𝕠𝕡 𝟙 𝔾𝕠𝕕🏆꧂', style: 'Top 1 God' },
        { name: '⚡𝓡𝓾𝓼𝓱 𝓚𝓲𝓷𝓰⚡', style: 'Rush King' },
        { name: '☠️𝕊𝕢𝕦𝕒𝕕 𝕎𝕚𝕡𝕖𝕣☠️', style: 'Squad Wiper' },
        { name: '꧁☬𝙿𝚛𝚘 𝙱𝚎𝚊𝚜𝚝☬꧂', style: 'Pro Beast' },
        { name: '⚡𝓒𝓵𝓾𝓽𝓬𝓱 𝓖𝓸𝓭⚡', style: 'Clutch God' },
    ],
};
