// Tool page definitions for specific font generators

export interface ToolPage {
    slug: string;
    name: string;
    emoji: string;
    description: string;
    metaTitle: string;
    metaDescription: string;
    heroText: string;
    charMapCategory: string; // maps to charMaps category
}

export const tools: ToolPage[] = [
    {
        slug: 'gothic',
        name: 'Gothic Font Generator',
        emoji: '☠',
        description: 'Dark & blackletter gothic fonts',
        metaTitle: 'Gothic Font Generator | Dark & Blackletter Fonts ☠',
        metaDescription: 'Generate gothic and blackletter fonts with our free tool. Create dark, medieval-style text for gaming, social media, and more. Copy and paste instantly!',
        heroText: 'Embrace the dark side with gothic blackletter fonts. Medieval-style text that adds mystery and power to any profile.',
        charMapCategory: 'gothic',
    },
    {
        slug: 'cursive',
        name: 'Cursive Font Generator',
        emoji: '✍️',
        description: 'Elegant cursive and script fonts',
        metaTitle: 'Cursive Font Generator | Elegant Handwriting Fonts ✍️',
        metaDescription: 'Create beautiful cursive and script fonts. Elegant handwriting-style text for Instagram, WhatsApp, and social media bios. Free copy and paste!',
        heroText: 'Add elegance to your text with beautiful cursive fonts. Handwriting-style scripts that look stunning anywhere.',
        charMapCategory: 'fancy',
    },
    {
        slug: 'bubble',
        name: 'Bubble Text Generator',
        emoji: '🫧',
        description: 'Circled and bubble letter fonts',
        metaTitle: 'Bubble Text Generator | Circled Letter Fonts 🫧',
        metaDescription: 'Generate bubble and circled letter text with our free tool. Fun, rounded letter styles perfect for social media and messaging. Copy and paste!',
        heroText: 'Make your text pop with fun bubble letters! Circled, rounded, and playful fonts that add personality to your messages.',
        charMapCategory: 'bubble',
    },
    {
        slug: 'emoji',
        name: 'Emoji Font Generator',
        emoji: '😍',
        description: 'Text with emoji-style decorations',
        metaTitle: 'Emoji Font Generator | Emoji Block Letters 😍',
        metaDescription: 'Generate emoji-style text and block letters. Fun and colorful text styles with emoji decorations. Free copy and paste font generator!',
        heroText: 'Turn your text into emoji block letters! Fun, colorful, and eye-catching styles perfect for social media posts.',
        charMapCategory: 'emoji',
    },
    {
        slug: 'bold',
        name: 'Bold Font Generator',
        emoji: '💪',
        description: 'Bold and strong Unicode fonts',
        metaTitle: 'Bold Font Generator | Strong & Powerful Text Fonts 💪',
        metaDescription: 'Generate bold Unicode fonts for social media, bios, and messaging. Strong, powerful text that stands out. Free copy and paste!',
        heroText: 'Make a bold statement with powerful Unicode fonts. Strong, eye-catching text that demands attention.',
        charMapCategory: 'bold',
    },
    {
        slug: 'upside-down',
        name: 'Upside Down Text Generator',
        emoji: '🙃',
        description: 'Flipped and reversed text',
        metaTitle: 'Upside Down Text Generator | Flipped Text 🙃',
        metaDescription: 'Flip your text upside down with our free generator. Create reversed and inverted text for fun social media posts. Copy and paste!',
        heroText: 'Flip your world upside down! Create inverted text that catches attention and adds a fun twist to your messages.',
        charMapCategory: 'weird',
    },
    {
        slug: 'glitch',
        name: 'Glitch Text Generator',
        emoji: '👾',
        description: 'Zalgo and glitch-style text',
        metaTitle: 'Glitch Text Generator | Zalgo & Corrupted Text 👾',
        metaDescription: 'Generate glitch and Zalgo text with our free tool. Create spooky, corrupted-looking text effects. Copy and paste glitch text instantly!',
        heroText: 'Create eerie glitch effects with corrupted text styles. Perfect for horror themes, gaming, and making your text look hauntingly unique.',
        charMapCategory: 'weird',
    },
    {
        slug: 'small',
        name: 'Small Text Generator',
        emoji: '🔍',
        description: 'Tiny superscript and subscript text',
        metaTitle: 'Small Text Generator | Tiny & Mini Text Fonts 🔍',
        metaDescription: 'Generate tiny and small text with superscript and subscript fonts. Create mini text for social media bios and usernames. Free copy paste!',
        heroText: 'Go small with tiny text styles! Superscript, subscript, and miniature fonts that add a subtle, unique touch to your profile.',
        charMapCategory: 'small',
    },
    {
        slug: 'magic',
        name: 'Magic Font Generator',
        emoji: '🪄',
        description: 'Mystical and enchanted fonts',
        metaTitle: 'Magic Font Generator | Mystical & Enchanted Fonts 🪄',
        metaDescription: 'Generate magical and enchanted fonts with mystical symbols. Create spellbinding text for social media and gaming. Free copy paste!',
        heroText: 'Cast a spell with magical font styles! Mystical symbols, enchanted letters, and designs straight from a fantasy world.',
        charMapCategory: 'magic',
    },
    {
        slug: 'aesthetic',
        name: 'Aesthetic Font Generator',
        emoji: '🌊',
        description: 'Vaporwave and aesthetic text',
        metaTitle: 'Aesthetic Font Generator | Vaporwave & Dreamy Fonts 🌊',
        metaDescription: 'Generate aesthetic and vaporwave text with dreamy fonts. Perfect for Tumblr, Instagram, and artistic profiles. Free copy paste!',
        heroText: 'Feed your aesthetic soul with dreamy vaporwave fonts. Wide text, soft vibes, and styles that match your artistic energy.',
        charMapCategory: 'aesthetic',
    },
    {
        slug: 'badass',
        name: 'Badass Font Generator',
        emoji: '💀',
        description: 'Dark and edgy badass fonts',
        metaTitle: 'Badass Font Generator | Dark & Edgy Text Styles 💀',
        metaDescription: 'Generate badass and edgy fonts with dark symbols. Create intimidating text for gaming, Discord, and social media. Free copy paste!',
        heroText: 'Embrace your dark side with badass font styles. Intimidating text, edgy symbols, and designs that command respect.',
        charMapCategory: 'badass',
    },
    {
        slug: 'tattoo',
        name: 'Tattoo Font Generator',
        emoji: '💉',
        description: 'Tattoo-style gothic and script fonts',
        metaTitle: 'Tattoo Font Generator | Ink-Style Gothic & Script Fonts 💉',
        metaDescription: 'Generate tattoo-style fonts with gothic and script lettering. Preview unique tattoo text designs. Free copy and paste!',
        heroText: 'Preview your next tattoo with beautiful gothic and script fonts. Ink-style lettering that looks stunning on screen and skin.',
        charMapCategory: 'tattoo',
    },
    {
        slug: 'number',
        name: 'Number Font Generator',
        emoji: '🔢',
        description: 'Styled numbers and digit fonts',
        metaTitle: 'Number Font Generator | Styled Digit Fonts 🔢',
        metaDescription: 'Generate styled number fonts with unique digit styles. Keycap, circled, and decorative number fonts. Free copy paste!',
        heroText: 'Style your numbers with unique digit fonts! Keycap numbers, circled digits, and decorative number styles.',
        charMapCategory: 'number',
    },
    {
        slug: 'line',
        name: 'Line Font Generator',
        emoji: '📏',
        description: 'Underline and line-decorated text',
        metaTitle: 'Line Font Generator | Underlined & Decorated Text 📏',
        metaDescription: 'Generate line-decorated text with underlines, overlines, and strikethrough effects. Unique text decorations. Free copy paste!',
        heroText: 'Add lines and decorations to your text! Underlines, overlines, and line effects that add visual structure to your names.',
        charMapCategory: 'line',
    },
    {
        slug: 'joiner',
        name: 'Joiner Font Generator',
        emoji: '🔗',
        description: 'Connected and joined letter fonts',
        metaTitle: 'Joiner Font Generator | Connected Letter Fonts 🔗',
        metaDescription: 'Generate connected and joined letter fonts with dots and linking characters. Unique chained text styles. Free copy paste!',
        heroText: 'Connect your letters with joiner fonts! Dotted links, connected characters, and flowing text styles.',
        charMapCategory: 'joiner',
    },
    {
        slug: 'retro',
        name: 'Retro Font Generator',
        emoji: '🕹️',
        description: 'Retro and pixel-style fonts',
        metaTitle: 'Retro Font Generator | Pixel & Arcade Style Fonts 🕹️',
        metaDescription: 'Generate retro and pixel-style fonts inspired by classic arcade games. Nostalgic text for gaming profiles. Free copy paste!',
        heroText: 'Travel back in time with retro pixel fonts! Arcade-style letters, classic gaming text, and nostalgic designs.',
        charMapCategory: 'retro',
    },
    {
        slug: 'halo',
        name: 'Halo Font Generator',
        emoji: '😇',
        description: 'Angel and halo-decorated fonts',
        metaTitle: 'Halo Font Generator | Angel & Heavenly Fonts 😇',
        metaDescription: 'Generate halo and angel-themed fonts with heavenly symbols. Angelic text with halo decorations. Free copy paste!',
        heroText: 'Float like an angel with heavenly halo fonts! Divine symbols, angelic letters, and celestial designs.',
        charMapCategory: 'fancy',
    },
    {
        slug: 'ice',
        name: 'Ice Font Generator',
        emoji: '❄️',
        description: 'Frozen and ice-themed fonts',
        metaTitle: 'Ice Font Generator | Frozen & Winter Style Fonts ❄️',
        metaDescription: 'Generate ice and frozen-themed fonts with winter symbols. Cool, frosty text for your profile. Free copy and paste!',
        heroText: 'Freeze your text with icy font styles! Snowflakes, frost effects, and winter-themed designs that chill any profile.',
        charMapCategory: 'cool',
    },
    {
        slug: 'pretty',
        name: 'Pretty Font Generator',
        emoji: '🌸',
        description: 'Beautiful and elegant pretty fonts',
        metaTitle: 'Pretty Font Generator | Beautiful & Elegant Fonts 🌸',
        metaDescription: 'Generate pretty and beautiful fonts with elegant script styles. Perfect for Instagram bio and social media. Free copy paste!',
        heroText: 'Make everything pretty with beautiful elegant fonts! Soft scripts, delicate designs, and gorgeously styled text.',
        charMapCategory: 'pretty',
    },
    {
        slug: 'big-text',
        name: 'Big Text / ASCII Art Generator',
        emoji: '🔤',
        description: 'Large block-letter ASCII art text',
        metaTitle: 'Big Text Generator | ASCII Art Block Letters 🔤',
        metaDescription: 'Generate big text and ASCII art block letters. Create large, eye-catching text art for Discord, gaming, and social media. Free!',
        heroText: 'Go BIG with massive ASCII art letters! Block-style text that dominates chats, Discord servers, and social media posts.',
        charMapCategory: 'bold',
    },
];

