// 500+ Plain-text trending name suggestions organized by mood/category
// Users click these → they auto-fill the input → site generates styled versions
// Curated from popular gaming, social media & profile name trends

export interface TrendingCategory {
    id: string;
    label: string;
    emoji: string;
    names: string[];
}

export const trendingCategories: TrendingCategory[] = [
    {
        id: 'gaming',
        label: 'Gaming',
        emoji: '🎮',
        names: [
            'Dark Knight', 'Shadow Hunter', 'Phantom Reaper', 'Night Hawk',
            'Storm Breaker', 'Blaze Storm', 'Toxic Viper', 'Sniper King',
            'Ghost Rider', 'Ninja', 'War Machine', 'Iron Fist',
            'Thunder Bolt', 'Dead Shot', 'Alpha Wolf', 'Bullet Proof',
            'Dark Angel', 'Berserker', 'Fire Dragon', 'Demon Slayer',
            'Shadow Rogue', 'Grim Slayer', 'Abyss Warden', 'Void Warlock',
            'Dusk Harbinger', 'Dark Nemesis', 'Quantum Ninja', 'Stealth Raptor',
            'Ghost Blade', 'Night Shade', 'Silent Fang', 'Shadow Strike',
            'Nocturne', 'Midnight Claw', 'Apex Sniper', 'Silent Scope',
            'Zero Recoil', 'One Shot Wonder', 'Rogue Warrior', 'Venom Strike',
            'Chaos Master', 'Blade Runner', 'Vortex King', 'Soul Reaper',
            'Death Dealer', 'Blood Moon', 'Night Fury', 'Savage Beast',
            'Dark Ops', 'Phoenix Rise', 'Titan Fall', 'Warlord',
            'Battle Cry', 'Kill Switch', 'Cross Fire', 'Head Hunter',
        ],
    },
    {
        id: 'attitude',
        label: 'Attitude',
        emoji: '😎',
        names: [
            'Bad Boy', 'Boss Man', 'Lone Wolf', 'Rebel King',
            'Savage King', 'Silent Killer', 'Heartless Boy', 'Attitude King',
            'Dangerous Boy', 'Dark Soul', 'Fearless', 'Untouchable',
            'Rule Breaker', 'Born To Win', 'King Of Kings', 'No Limits',
            'Maverick', 'Ice Cold Heart', 'Trouble Maker', 'Wild Child',
            'Reckless', 'Outlaw', 'Beast Mode', 'Unbreakable',
            'Ruthless King', 'Toxic Boy', 'No Mercy', 'Stone Cold',
            'Silent Storm', 'Zero Feelings', 'Not Your Type', 'Mr Perfect',
            'King Slayer', 'Alpha Male', 'Power Player', 'Game Changer',
            'Dominator', 'Unstoppable', 'Villain', 'Last Standing',
            'Legend Killer', 'Ego King', 'Bold Spirit', 'Fierce Lion',
            'Rebel Soul', 'Ruthless Mind', 'Shadow Boss', 'Iron Will',
        ],
    },
    {
        id: 'sad',
        label: 'Sad',
        emoji: '😢',
        names: [
            'Alone Bird', 'Broken Heart', 'Lost Soul', 'Silent Tears',
            'Sad Boy', 'Lonely Star', 'Empty Heart', 'Broken Angel',
            'Faded Dreams', 'Crying Soul', 'Pain Killer', 'Dark Shadow',
            'Shattered Heart', 'Forgotten Soul', 'Sleepless Night', 'Invisible',
            'Broken Whispers', 'Hollow Heart', 'Crimson Regret', 'Wounded Spirit',
            'Fractured Dreams', 'Fading Echo', 'Lost In Thought', 'Drowning In Silence',
            'Numb Wanderer', 'Empty Chapters', 'Melancholy Mind', 'Silent Screams',
            'Frozen Tears', 'Bitter Goodbye', 'Fragile Soul', 'Dying Inside',
            'Fading Light', 'Sunken Void', 'Wilted Rose', 'Torn Pages',
            'Bleeding Memories', 'Shattered Hope', 'Weary Eyes', 'Eclipse Soul',
            'Raven Grief', 'Void Whisper', 'Black Rose', 'Abyss Of Pain',
            'Darkened Skies', 'Phantom Pain', 'Haunted Past', 'Fading Memories',
        ],
    },
    {
        id: 'happy',
        label: 'Happy',
        emoji: '😊',
        names: [
            'Sunshine', 'Happy Soul', 'Smiley Face', 'Good Vibes',
            'Lucky Star', 'Golden Heart', 'Joyful', 'Bright Star',
            'Sparkling', 'Sweet Dream', 'Rainbow', 'Blissful',
            'Cheerful', 'Positive Vibes', 'Starlight', 'Pure Joy',
            'Morning Dew', 'Laughing Soul', 'Cloud Nine', 'Happy Camper',
            'Sunny Day', 'Smiling Eyes', 'Free Spirit', 'Dancing Star',
            'Joy Ride', 'Merry Heart', 'Bloom Day', 'Bright Side',
            'Warm Hug', 'Sweet Melody', 'Happy Feet', 'Rising Sun',
            'Golden Sunrise', 'Sparkle Queen', 'Daydreamer', 'Sunkissed',
            'Laughter Queen', 'Jolly Soul', 'Giggles', 'Peachy Vibes',
        ],
    },
    {
        id: 'love',
        label: 'Love',
        emoji: '❤️',
        names: [
            'My Queen', 'King Of Hearts', 'Love Bird', 'Sweet Heart',
            'Baby Doll', 'Honey Bear', 'Prince Charming', 'Cutie Pie',
            'Angel Eyes', 'Love Bug', 'Soul Mate', 'Dream Girl',
            'My Valentine', 'Heart Breaker', 'Love Story', 'Forever Yours',
            'Hopeless Romantic', 'Kiss Me', 'True Love', 'Love Machine',
            'Heart Stealer', 'Romeo', 'Juliet', 'Lovesick',
            'Crazy In Love', 'Sweet Nothings', 'My Sunshine', 'Heart Throb',
            'Endless Love', 'Cupid Arrow', 'My Everything', 'Sugar Lips',
            'First Kiss', 'Roses For You', 'Love Drunk', 'Dream Lover',
            'My World', 'Heart Song', 'Love Potion', 'Beloved',
        ],
    },
    {
        id: 'cool',
        label: 'Cool',
        emoji: '❄️',
        names: [
            'Black Knight', 'Ice Cold', 'Shadow King', 'Dark Horse',
            'Frost Bite', 'Cool Dude', 'Steel Mind', 'Arctic Fox',
            'Zero Chill', 'Night Rider', 'Slick Rick', 'Snow Wolf',
            'Cold Blooded', 'Sharp Shooter', 'Smooth Criminal', 'Royal Elite',
            'Ghost Protocol', 'Neon Rider', 'Silent Arrow', 'Cold Front',
            'Iron Heart', 'Black Ice', 'Dark Matter', 'Midnight King',
            'Crystal Clear', 'Polar Bear', 'Frozen King', 'Ice Breaker',
            'Cool Breeze', 'Diamond Mind', 'Sterling', 'Silver Bullet',
            'Titanium Soul', 'Chrome Heart', 'Dark Wizard', 'Electric Shock',
            'Neon Lights', 'Shadow Walker', 'Night Owl', 'Cyber Punk',
        ],
    },
    {
        id: 'mafia',
        label: 'Mafia',
        emoji: '🔫',
        names: [
            'Mafia Boss', 'The Godfather', 'Don Corleone', 'Gangster',
            'The Don', 'Mafia King', 'Dark Mafia', 'Crime Lord',
            'Mob Boss', 'Silent Mafia', 'Scarface', 'Big Boss',
            'Underworld', 'The Outlaw', 'Death Dealer', 'Mafia Lord',
            'Hitman', 'Trigger Happy', 'Blood Money', 'Night Stalker',
            'Gun Slinger', 'Street King', 'Crime Boss', 'Thug Life',
            'Al Capone', 'Lucky Luciano', 'Vito', 'Tommy Gun',
            'Kingpin', 'Made Man', 'Capo', 'Tony Montana',
            'Criminal Mind', 'Dark Empire', 'Godmother', 'The Enforcer',
            'Bullet King', 'War Lord', 'Street Soldier', 'Night Mafia',
        ],
    },
    {
        id: 'girl',
        label: 'Girl',
        emoji: '👧',
        names: [
            'Princess', 'Queen Bee', 'Butterfly Girl', 'Sweet Angel',
            'Cute Doll', 'Star Girl', 'Pink Princess', 'Dream Girl',
            'Baby Girl', 'Diamond Girl', 'Rose Queen', 'Fairy',
            'Glam Girl', 'Lovely Girl', 'Moon Light', 'Angel Face',
            'Sugar Plum', 'Flower Power', 'Miss Sunshine', 'Dancing Queen',
            'Cherry Blossom', 'Daisy Girl', 'Crystal Heart', 'Melody Queen',
            'Sparkle Eyes', 'Cotton Candy', 'Lady Boss', 'Diva',
            'Goddess', 'Little Star', 'Beauty Queen', 'Sweet Rose',
            'Honey Bee', 'Mystic Girl', 'Velvet Rose', 'Pearl Girl',
            'Snow White', 'Luna Girl', 'Blossom', 'Flower Child',
            'Miss Elegance', 'Galaxy Girl', 'Ice Princess', 'Petal',
            'Stardust', 'Orchid', 'Sapphire Girl', 'Golden Girl',
        ],
    },
    {
        id: 'boy',
        label: 'Boy',
        emoji: '👦',
        names: [
            'Royal King', 'Dark Prince', 'Alpha Male', 'Boss Boy',
            'Stylish Boy', 'Rebel', 'Hunter', 'Brave Heart',
            'King Size', 'Champion', 'Warrior', 'Legend',
            'Thunder King', 'Iron Man', 'Smart Boy', 'Captain',
            'Gentleman', 'Mr Handsome', 'Prince', 'Magnet Boy',
            'Rockstar', 'Cool Boy', 'Dashing', 'Power Boy',
            'Flash', 'Tiger Boy', 'Phoenix King', 'Eagle Eye',
            'Sharp Mind', 'Storm King', 'Master Mind', 'Steel Boy',
            'Crown Prince', 'Hero', 'Gladiator', 'Falcon',
            'Blaze King', 'Ace', 'Maverick Boy', 'Silver Fox',
        ],
    },
    {
        id: 'couple',
        label: 'Couple',
        emoji: '💑',
        names: [
            'King And Queen', 'His Queen Her King', 'Bonnie And Clyde',
            'Beauty And Beast', 'Romeo And Juliet', 'Sun And Moon',
            'Thunder And Lightning', 'Coffee And Cream', 'Rose And Thorn',
            'Mickey And Minnie', 'Salt And Pepper', 'Sweet And Sour',
            'Day And Night', 'Fire And Ice', 'Peanut Butter And Jelly',
            'Sugar And Spice', 'Lock And Key', 'Stars And Moon',
            'Honey And Bunny', 'Prince And Princess', 'Mr And Mrs',
            'Cookie And Cream', 'Bow And Arrow', 'Cloud And Rain',
            'Heart And Soul', 'Yin And Yang', 'Adam And Eve',
            'Forever Together', 'Better Half', 'Two Hearts One Love',
            'My King My Queen', 'Soul Mates', 'Power Couple',
            'Crowned Hearts', 'Royal Sweethearts', 'Together Forever',
            'Love Warriors', 'Perfect Match', 'Dream Team', 'Ride Or Die',
        ],
    },
    {
        id: 'aesthetic',
        label: 'Aesthetic',
        emoji: '🌸',
        names: [
            'Velvet Sky', 'Lavender Moon', 'Honey Pearl', 'Paper Fern',
            'Midsommar Skies', 'Pastel Peach', 'Minty Melody', 'Blush Clouds',
            'Cream Sugar', 'Honey Dust', 'Fairy Light', 'Twinkle Star',
            'Moon Kitten', 'Cozy Marshy', 'Dream Sprinkle', 'Fluffy Cloud',
            'Petal Glow', 'Aurora Vibes', 'Misty Opal', 'Silver Sunrise',
            'Starlit Dreamer', 'Snow Essence', 'Dreamy Pearl', 'Golden Whisper',
            'Lunar Velvet', 'Sunset Gleam', 'Petal Haze', 'Moonlit Breeze',
            'Frost Glow', 'Cloud Wisp', 'Ember Lush', 'Rose Gleam',
            'Lilac Whim', 'Pale Dawn', 'Dove Glim', 'Ivy Breeze',
            'Celestial Charm', 'Frosted Meadow', 'Blossom Wave', 'Cosmic Bloom',
            'Velvet Lullaby', 'Indigo Dream', 'Feathered Echo', 'Silk Whisper',
            'Cherry Sky', 'Bamboo Rain', 'Gentle Tide', 'Wild Orchid',
        ],
    },
    {
        id: 'dark',
        label: 'Dark',
        emoji: '🖤',
        names: [
            'Void Walker', 'Cursed Ivy', 'Dead Roses', 'Ash Lynx',
            'Raven Hush', 'Bitter Wilt', 'Hollow Dame', 'Bruised Moon',
            'Dark Gaze', 'Frost Fawn', 'Moth Halo', 'Gothic Whisper',
            'Wraith Rose', 'Poison Moon', 'Ghost Ling', 'Drown Meadow',
            'Decay Poetry', 'Dusk Sigh', 'Shadow Edge', 'Ashes And Lace',
            'Grim Glimmer', 'Plague Petal', 'Eldritch Rose', 'Dreamy Decay',
            'Velvet Remains', 'Gloom Kissed', 'Death And Daisy', 'Tragic Dust',
            'Eerie Orchid', 'Cold Ethereal', 'Haunted Wilt', 'Wrath In Lace',
            'Venom Rose', 'Midnight Ember', 'Obsidian Heart', 'Crimson Thorn',
            'Dark Bloom', 'Fallen Grace', 'Night Phantom', 'Shadow Flame',
            'Blood Orchid', 'Dark Serenade', 'Cursed Soul', 'Wicked Night',
            'Sinister Grace', 'Grim Reaper', 'Hollow King', 'Lost Phantom',
        ],
    },
    {
        id: 'pubg',
        label: 'PUBG',
        emoji: '🎯',
        names: [
            'Headshot King', 'Chicken Dinner', 'Drop Zone', 'Loot King',
            'AWM Master', 'Pan Warrior', 'Bridge Camper', 'Last Man Standing',
            'Kar98 King', 'Scope Master', 'Zone Runner', 'Nade King',
            'M416 Pro', 'Rush King', 'Clutch God', 'Kill Machine',
            'Snake Player', 'Prone King', 'Third Party', 'Hot Drop',
            'Supply Drop', 'Red Zone', 'Flare Gun', 'Molotov King',
            'Groza Beast', 'M24 Sniper', 'AKM Pro', 'Mini14 God',
            'Uzi Rush', 'Vector King', 'Camp Master', 'Solo King',
            'Squad Leader', 'Duo Master', 'Map Runner', 'Ghillie Suit',
            'Bolt Action', 'Hip Fire King', 'Spray Master', 'Recoil King',
        ],
    },
    {
        id: 'freefire',
        label: 'Free Fire',
        emoji: '🔥',
        names: [
            'Raistar', 'Head Hunter', 'Fire Storm', 'Speed King',
            'Booyah King', 'Diamond King', 'Rush Master', 'Garena Pro',
            'Auto King', 'Snipe Lord', 'Battle Star', 'Fire Lord',
            'Dragon Fire', 'One Tap King', 'Quick Scope', 'Rank Pusher',
            'Gloo Wall Pro', 'Chrono King', 'DJ Alok', 'K Character',
            'M1887 King', 'MP40 Pro', 'Shotgun God', 'Grenade King',
            'Clash Squad', 'Battle Royale', 'Custom Room', 'Top Global',
            'Heroic Push', 'Grandmaster', 'Zone Fighter', 'Loot Runner',
            'Drop King', 'Shield Wall', 'Fire Starter', 'Blaze Runner',
            'Solo Master', 'Rush God', 'Kill Leader', 'Victory King',
        ],
    },
    {
        id: 'thankful',
        label: 'Thankful',
        emoji: '🙏',
        names: [
            'Blessed Soul', 'Grateful Heart', 'Thank God', 'Divine Grace',
            'Humble King', 'Blessed Life', 'Gods Gift', 'Heavenly',
            'Peaceful Soul', 'Faith Walker', 'Grace', 'Miracle',
            'Blessed One', 'Pure Soul', 'Angel', 'Holy Spirit',
            'Prayer Warrior', 'Graceful', 'Spirit Led', 'Praise God',
            'God First', 'Anointed', 'Chosen One', 'Faithful',
            'Light Of God', 'Living Faith', 'Grace Wins', 'Mercy',
            'Redeemed', 'Born Again', 'Favor Of God', 'Heavens Child',
            'Trust In God', 'Hope', 'Praying Hands', 'Saved',
            'Kingdom Come', 'God Is Good', 'Worship King', 'Hallelujah',
        ],
    },
    {
        id: 'funny',
        label: 'Funny',
        emoji: '😂',
        names: [
            'Loading Brain', 'Ctrl Alt Delete', 'Not A Robot', 'Error 404',
            'Sleeping Beauty', 'Couch Potato', 'Lazy Genius', 'Drama Queen',
            'Nap King', 'Pizza Lover', 'WiFi Warrior', 'Google Me',
            'Pro Sleeper', 'Snack Attack', 'Meme Lord', 'Potato Head',
            'Captain Obvious', 'Cereal Killer', 'Sir Laughs A Lot', 'No Filter',
            'Procrastinator', 'Chai Lover', 'Biryani Boy', 'Roti Gang',
            'Netflix Addict', 'Noob Gamer', 'Keyboard Warrior', 'Copy Paste',
            'Ban Me Bro', 'Aim Bot', 'AFK King', 'Rage Quit',
            'Spam King', 'Lag Master', 'Noob Slayer', 'Bug Hunter',
            'Last Seen', 'Buffering', 'Please Wait', 'Currently Offline',
        ],
    },
    {
        id: 'motivational',
        label: 'Motivation',
        emoji: '💪',
        names: [
            'Never Give Up', 'Rise Again', 'Dream Big', 'Stay Strong',
            'Hustle Hard', 'Self Made', 'Dream Chaser', 'Goal Digger',
            'Success', 'No Pain No Gain', 'Keep Going', 'Stay Focused',
            'Believe', 'Work Hard', 'Grind Mode', 'Limitless',
            'Overcome', 'Power House', 'Level Up', 'Game On',
            'Warrior Spirit', 'Champion Mind', 'Boss Moves', 'Empire Builder',
            'Iron Mind', 'Rise Up', 'Fight Back', 'Go Getter',
            'Money Maker', 'Millionaire Mind', 'King Mentality', 'Top G',
            'Win Or Learn', 'Sigma Male', 'Hard Worker', 'Earn It',
            'Discipline King', 'Focus Mode', 'Grind Daily', 'Legend Mode',
        ],
    },
    {
        id: 'anime',
        label: 'Anime',
        emoji: '⚔️',
        names: [
            'Naruto Uzumaki', 'Sasuke', 'Itachi Uchiha', 'Goku',
            'Vegeta', 'Light Yagami', 'L Lawliet', 'Levi Ackerman',
            'Eren Yeager', 'Kaneki Ken', 'Saitama', 'Spike Spiegel',
            'Tanjiro', 'Gojo Satoru', 'Sukuna', 'Zoro',
            'Luffy', 'Shanks', 'Kakashi', 'Madara',
            'Deku', 'All Might', 'Todoroki', 'Bakugo',
            'Akatsuki', 'Sharingan Eye', 'Sage Mode', 'Rasengan',
            'Hollow King', 'Bankai Master', 'Titan Slayer', 'Demon King',
            'Shadow Monarch', 'Spirit Fox', 'Dragon Ball', 'Chakra King',
            'Cursed Spirit', 'Infinity', 'Black Flash', 'Domain King',
        ],
    },
    {
        id: 'wifi',
        label: 'WiFi',
        emoji: '📶',
        names: [
            'Tell My WiFi Love Her', 'Pretty Fly For A WiFi',
            'FBI Surveillance Van', 'Loading Please Wait',
            'Drop It Like Its Hotspot', 'Get Off My LAN',
            'WiFi So Serious', 'The Promised LAN',
            'No Free WiFi', 'Hack Me If You Can',
            'Router I Hardly Know Her', 'Bill Wi The Science Fi',
            'Abraham Linksys', 'Martin Router King',
            'WiFi Art Thou Romeo', 'The LAN Before Time',
            'Silence Of The LANs', 'House LANnister',
            'LAN Of The Free', 'Nacho WiFi',
            'New England Clam Router', 'LAN Solo',
            'The Dark KnightRises WiFi', 'WiFi Bringer',
            'Keep It On The Download', 'Go Go Gadget Internet',
            'Bandwidth Together', 'Dunder MiffLAN',
            'This LAN Is My LAN', 'Lord Of The Pings',
            'The Ping In The North', 'Darude LAN Storm',
            'Byte Me', 'Password Is Password',
            'Searching For Signal', 'Free Virus',
            'Click Here For WiFi', 'Mom Use This One',
            'Not The WiFi You Looking For', 'It Burns When IP',
        ],
    },
    {
        id: 'group',
        label: 'Group',
        emoji: '👥',
        names: [
            'The Avengers', 'Squad Goals', 'Dream Team', 'Wolf Pack',
            'Power Rangers', 'Justice League', 'Elite Squad', 'Night Riders',
            'Thunder Squad', 'Dark Knights', 'Dragon Warriors', 'Fire Squad',
            'Legends Only', 'Royal Family', 'The Untouchables', 'Kings Gang',
            'Battle Buddies', 'Brothers In Arms', 'Savage Squad', 'Wild Ones',
            'No Mercy Crew', 'Storm Troopers', 'Fearless Five', 'Beast Squad',
            'Alpha Team', 'Venom Squad', 'Ghost Riders', 'Shadow Warriors',
            'Hunter Gang', 'Rebel Alliance', 'Chaos Crew', 'Blood Brothers',
            'Steel Legion', 'Warrior Clan', 'Night Wolves', 'Death Squad',
            'Kill Squad', 'Skull Gang', 'Blade Runners', 'Iron Legion',
        ],
    },
];
